services:
  zookeeper:
    restart: always
    image: zookeeper:3.7
    hostname: zookeeper
    volumes:
      - "zookeeper:/data"
  clickhouse-server:
    user: root
    restart: on-failure
    image: clickhouse/clickhouse-server:24.5.1.1763
    hostname: clickhouse-server
    links:
      - zookeeper
    depends_on:
      - zookeeper
    healthcheck:
      test: [ "CMD", "bash", "-c", "clickhouse-client --query \"SELECT value FROM system.settings WHERE name = 'readonly'\" | grep -q '0'" ]
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - "./clickhouse/config.xml:/etc/clickhouse-server/config.xml:ro"
      - "./clickhouse/conf.d:/etc/clickhouse-server/conf.d:ro"
      - "clickhouse:/clickhouse/"

  clickhouse-init:
    image: clickhouse/clickhouse-server
    entrypoint: [ './migrations.sh' ]
    restart: on-failure
    depends_on:
      clickhouse-server:
        condition: service_healthy
      zookeeper:
        condition: service_started
    links:
      - zookeeper
    volumes:
      - "./clickhouse/migrations.sh:/migrations.sh:ro"
      - "../migrations/stats:/migrations:ro"
      - "state:/state/"
  clickhouse-dump:
    image: clickhouse/clickhouse-server
    entrypoint: [ './dump.sh' ]
    restart: on-failure
    depends_on:
      clickhouse-server:
        condition: service_healthy
      zookeeper:
        condition: service_started
    links:
      - zookeeper
    volumes:
      - "./clickhouse/dump.sh:/dump.sh:ro"
      - "./clickhouse/user_files/dump.csv:/clickhouse/user_files/dump.csv:ro"
      - "state:/state/"
  archivarius:
    image: adnet-project/archivarius:latest
    depends_on:
      clickhouse-server:
        condition: service_healthy
      clickhouse-init:
        condition: service_started
    ports:
      - "9500:9500"
volumes:
  clickhouse:
    driver: local
  state:
    driver: local
  zookeeper:
    driver: local