// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.3
// source: protocol/archivarius.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	ArchivariusService_Statistic_FullMethodName = "/archivarius.ArchivariusService/Statistic"
)

// ArchivariusServiceClient is the client API for ArchivariusService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service defining the Archivarius API.
type ArchivariusServiceClient interface {
	// Fetches statistical data based on the provided request.
	Statistic(ctx context.Context, in *StatisticRequest, opts ...grpc.CallOption) (*StatisticResponse, error)
}

type archivariusServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewArchivariusServiceClient(cc grpc.ClientConnInterface) ArchivariusServiceClient {
	return &archivariusServiceClient{cc}
}

func (c *archivariusServiceClient) Statistic(ctx context.Context, in *StatisticRequest, opts ...grpc.CallOption) (*StatisticResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatisticResponse)
	err := c.cc.Invoke(ctx, ArchivariusService_Statistic_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// ArchivariusServiceServer is the server API for ArchivariusService service.
// All implementations must embed UnimplementedArchivariusServiceServer
// for forward compatibility.
//
// Service defining the Archivarius API.
type ArchivariusServiceServer interface {
	// Fetches statistical data based on the provided request.
	Statistic(context.Context, *StatisticRequest) (*StatisticResponse, error)
	mustEmbedUnimplementedArchivariusServiceServer()
}

// UnimplementedArchivariusServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedArchivariusServiceServer struct{}

func (UnimplementedArchivariusServiceServer) Statistic(context.Context, *StatisticRequest) (*StatisticResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Statistic not implemented")
}
func (UnimplementedArchivariusServiceServer) mustEmbedUnimplementedArchivariusServiceServer() {}
func (UnimplementedArchivariusServiceServer) testEmbeddedByValue()                            {}

// UnsafeArchivariusServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ArchivariusServiceServer will
// result in compilation errors.
type UnsafeArchivariusServiceServer interface {
	mustEmbedUnimplementedArchivariusServiceServer()
}

func RegisterArchivariusServiceServer(s grpc.ServiceRegistrar, srv ArchivariusServiceServer) {
	// If the following call pancis, it indicates UnimplementedArchivariusServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&ArchivariusService_ServiceDesc, srv)
}

func _ArchivariusService_Statistic_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatisticRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ArchivariusServiceServer).Statistic(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: ArchivariusService_Statistic_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ArchivariusServiceServer).Statistic(ctx, req.(*StatisticRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// ArchivariusService_ServiceDesc is the grpc.ServiceDesc for ArchivariusService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ArchivariusService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "archivarius.ArchivariusService",
	HandlerType: (*ArchivariusServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Statistic",
			Handler:    _ArchivariusService_Statistic_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protocol/archivarius.proto",
}
