package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.88

import (
	"context"

	"github.com/geniusrabbit/blaze-api/server/graphql/types"
	"github.com/sspserver/api/pkg/server/graphql/models"
)

// AcceptAgreement is the resolver for the acceptAgreement field.
func (r *mutationResolver) AcceptAgreement(ctx context.Context, codename string, date types.DateTime, signature string) (*models.Agreement, error) {
	return r.agreements.Accept(ctx, codename, date, signature)
}

// Agreement is the resolver for the agreement field.
func (r *queryResolver) Agreement(ctx context.Context, codename string) (*models.Agreement, error) {
	return r.agreements.Get(ctx, codename)
}

// ListAgreements is the resolver for the listAgreements field.
func (r *queryResolver) ListAgreements(ctx context.Context, accepted *bool) ([]*models.Agreement, error) {
	return r.agreements.List(ctx, accepted)
}

// NextAgreement is the resolver for the nextAgreement field.
func (r *queryResolver) NextAgreement(ctx context.Context) (*models.Agreement, error) {
	return r.agreements.NextAwailable(ctx)
}
