package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.92

import (
	"context"
	"fmt"

	"github.com/geniusrabbit/blaze-api/server/graphql/connectors"
	"github.com/geniusrabbit/blaze-api/server/graphql/models"
	"github.com/sspserver/api/pkg/server/graphql/generated"
)

// Edges is the resolver for the edges field.
func (r *authClientConnectionResolver) Edges(ctx context.Context, obj *connectors.CollectionConnection[*models.AuthClient]) ([]*models.AuthClientEdge, error) {
	panic(fmt.Errorf("not implemented: Edges - edges"))
}

// CreateAuthClient is the resolver for the createAuthClient field.
func (r *mutationResolver) CreateAuthClient(ctx context.Context, input models.AuthClientCreateInput) (*models.AuthClientPayload, error) {
	return r.authclients.CreateAuthClient(ctx, &input)
}

// UpdateAuthClient is the resolver for the updateAuthClient field.
func (r *mutationResolver) UpdateAuthClient(ctx context.Context, id string, input models.AuthClientUpdateInput) (*models.AuthClientPayload, error) {
	return r.authclients.UpdateAuthClient(ctx, id, &input)
}

// DeleteAuthClient is the resolver for the deleteAuthClient field.
func (r *mutationResolver) DeleteAuthClient(ctx context.Context, id string, msg *string) (*models.AuthClientPayload, error) {
	return r.authclients.DeleteAuthClient(ctx, id, msg)
}

// AuthClient is the resolver for the authClient field.
func (r *queryResolver) AuthClient(ctx context.Context, id string) (*models.AuthClientPayload, error) {
	return r.authclients.AuthClient(ctx, id)
}

// ListAuthClients is the resolver for the listAuthClients field.
func (r *queryResolver) ListAuthClients(ctx context.Context, filter *models.AuthClientListFilter, order []*models.AuthClientListOrder, page *models.Page) (*connectors.CollectionConnection[*models.AuthClient], error) {
	return r.authclients.ListAuthClients(ctx, filter, order, page)
}

// AuthClientConnection returns generated.AuthClientConnectionResolver implementation.
func (r *Resolver) AuthClientConnection() generated.AuthClientConnectionResolver {
	return &authClientConnectionResolver{r}
}

type authClientConnectionResolver struct{ *Resolver }
