package resolvers

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.92

import (
	"context"
	"fmt"

	"github.com/geniusrabbit/blaze-api/server/graphql/connectors"
	models1 "github.com/geniusrabbit/blaze-api/server/graphql/models"
	"github.com/sspserver/api/pkg/server/graphql/generated"
	"github.com/sspserver/api/pkg/server/graphql/models"
)

// Childrens is the resolver for the childrens field.
func (r *categoryResolver) Childrens(ctx context.Context, obj *models.Category) ([]*models.Category, error) {
	return r.categories.Childrens(ctx, obj)
}

// Edges is the resolver for the edges field.
func (r *categoryConnectionResolver) Edges(ctx context.Context, obj *connectors.CollectionConnection[*models.Category]) ([]*models.CategoryEdge, error) {
	panic(fmt.Errorf("not implemented: Edges - edges"))
}

// CreateCategory is the resolver for the createCategory field.
func (r *mutationResolver) CreateCategory(ctx context.Context, input models.CategoryInput) (*models.CategoryPayload, error) {
	return r.categories.Create(ctx, input)
}

// UpdateCategory is the resolver for the updateCategory field.
func (r *mutationResolver) UpdateCategory(ctx context.Context, id uint64, input models.CategoryInput) (*models.CategoryPayload, error) {
	return r.categories.Update(ctx, id, input)
}

// DeleteCategory is the resolver for the deleteCategory field.
func (r *mutationResolver) DeleteCategory(ctx context.Context, id uint64, msg *string) (*models.CategoryPayload, error) {
	return r.categories.Delete(ctx, id, msg)
}

// Category is the resolver for the category field.
func (r *queryResolver) Category(ctx context.Context, id uint64) (*models.CategoryPayload, error) {
	return r.categories.Get(ctx, id)
}

// ListCategories is the resolver for the listCategories field.
func (r *queryResolver) ListCategories(ctx context.Context, filter *models.CategoryListFilter, order *models.CategoryListOrder, page *models1.Page) (*connectors.CollectionConnection[*models.Category], error) {
	return r.categories.List(ctx, filter, order, page)
}

// Category returns generated.CategoryResolver implementation.
func (r *Resolver) Category() generated.CategoryResolver { return &categoryResolver{r} }

// CategoryConnection returns generated.CategoryConnectionResolver implementation.
func (r *Resolver) CategoryConnection() generated.CategoryConnectionResolver {
	return &categoryConnectionResolver{r}
}

type categoryResolver struct{ *Resolver }
type categoryConnectionResolver struct{ *Resolver }
