// Code generated by MockGen. DO NOT EDIT.
// Source: usecase.go
//
// Generated by this command:
//
//	mockgen -source usecase.go -package mocks -destination mocks/repository.go
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	zone "github.com/sspserver/api/pkg/repository/zone"
	models "github.com/sspserver/api/pkg/repository/zone/models"
	gomock "go.uber.org/mock/gomock"
)

// MockUsecase is a mock of Usecase interface.
type MockUsecase struct {
	ctrl     *gomock.Controller
	recorder *MockUsecaseMockRecorder
	isgomock struct{}
}

// MockUsecaseMockRecorder is the mock recorder for MockUsecase.
type MockUsecaseMockRecorder struct {
	mock *MockUsecase
}

// NewMockUsecase creates a new mock instance.
func NewMockUsecase(ctrl *gomock.Controller) *MockUsecase {
	mock := &MockUsecase{ctrl: ctrl}
	mock.recorder = &MockUsecaseMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockUsecase) EXPECT() *MockUsecaseMockRecorder {
	return m.recorder
}

// Approve mocks base method.
func (m *MockUsecase) Approve(ctx context.Context, id uint64, msg string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Approve", ctx, id, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Approve indicates an expected call of Approve.
func (mr *MockUsecaseMockRecorder) Approve(ctx, id, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Approve", reflect.TypeOf((*MockUsecase)(nil).Approve), ctx, id, msg)
}

// Count mocks base method.
func (m *MockUsecase) Count(ctx context.Context, qops ...zone.Option) (int64, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range qops {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "Count", varargs...)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Count indicates an expected call of Count.
func (mr *MockUsecaseMockRecorder) Count(ctx any, qops ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, qops...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Count", reflect.TypeOf((*MockUsecase)(nil).Count), varargs...)
}

// Create mocks base method.
func (m *MockUsecase) Create(ctx context.Context, obj *models.Zone) (uint64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, obj)
	ret0, _ := ret[0].(uint64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Create indicates an expected call of Create.
func (mr *MockUsecaseMockRecorder) Create(ctx, obj any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockUsecase)(nil).Create), ctx, obj)
}

// Delete mocks base method.
func (m *MockUsecase) Delete(ctx context.Context, id uint64, msg string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, id, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockUsecaseMockRecorder) Delete(ctx, id, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockUsecase)(nil).Delete), ctx, id, msg)
}

// FetchList mocks base method.
func (m *MockUsecase) FetchList(ctx context.Context, qops ...zone.Option) ([]*models.Zone, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range qops {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "FetchList", varargs...)
	ret0, _ := ret[0].([]*models.Zone)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// FetchList indicates an expected call of FetchList.
func (mr *MockUsecaseMockRecorder) FetchList(ctx any, qops ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, qops...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "FetchList", reflect.TypeOf((*MockUsecase)(nil).FetchList), varargs...)
}

// Get mocks base method.
func (m *MockUsecase) Get(ctx context.Context, id uint64) (*models.Zone, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, id)
	ret0, _ := ret[0].(*models.Zone)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockUsecaseMockRecorder) Get(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockUsecase)(nil).Get), ctx, id)
}

// GetByCodename mocks base method.
func (m *MockUsecase) GetByCodename(ctx context.Context, codename string) (*models.Zone, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByCodename", ctx, codename)
	ret0, _ := ret[0].(*models.Zone)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByCodename indicates an expected call of GetByCodename.
func (mr *MockUsecaseMockRecorder) GetByCodename(ctx, codename any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByCodename", reflect.TypeOf((*MockUsecase)(nil).GetByCodename), ctx, codename)
}

// Pause mocks base method.
func (m *MockUsecase) Pause(ctx context.Context, id uint64, msg string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Pause", ctx, id, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Pause indicates an expected call of Pause.
func (mr *MockUsecaseMockRecorder) Pause(ctx, id, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Pause", reflect.TypeOf((*MockUsecase)(nil).Pause), ctx, id, msg)
}

// Reject mocks base method.
func (m *MockUsecase) Reject(ctx context.Context, id uint64, msg string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reject", ctx, id, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Reject indicates an expected call of Reject.
func (mr *MockUsecaseMockRecorder) Reject(ctx, id, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reject", reflect.TypeOf((*MockUsecase)(nil).Reject), ctx, id, msg)
}

// Run mocks base method.
func (m *MockUsecase) Run(ctx context.Context, id uint64, msg string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx, id, msg)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockUsecaseMockRecorder) Run(ctx, id, msg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockUsecase)(nil).Run), ctx, id, msg)
}

// Update mocks base method.
func (m *MockUsecase) Update(ctx context.Context, id uint64, obj *models.Zone) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Update", ctx, id, obj)
	ret0, _ := ret[0].(error)
	return ret0
}

// Update indicates an expected call of Update.
func (mr *MockUsecaseMockRecorder) Update(ctx, id, obj any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Update", reflect.TypeOf((*MockUsecase)(nil).Update), ctx, id, obj)
}
