-- Generated by browserfix.py from browsers.json — do not edit by hand.
BEGIN;

CREATE UNIQUE INDEX IF NOT EXISTS type_browser_name_key ON type_browser (name);

-- Root browsers
INSERT INTO type_browser (name, version, description, match_name_exp, match_ua_exp, match_ver_min_exp, match_ver_max_exp, year_release, year_end_support, active, parent_id)
VALUES
  ('Internet Explorer', '', 'Microsoft Internet Explorer', 'Internet Explorer', '$regex$MSIE |Trident/', '', '', 1995, 2022, 'pause', NULL),
  ('Mozilla Firefox', '', 'Mozilla Firefox Web Browser', 'Firefox', '$regex$Firefox', '', '', 2004, 0, 'active', NULL),
  ('Google Chrome', '', 'Google Chrome Web Browser', 'Chrome', '$regex$Chrome', '', '', 2008, 0, 'active', NULL),
  ('Safari', '', 'Apple Safari Web Browser', 'Safari', '$regex$Safari', '', '', 2003, 0, 'active', NULL),
  ('Android Browser', '', 'Legacy AOSP Android Browser; browser versions must not be replaced with Android operating system versions', 'Android Browser', '$regex$Android Browser', '', '', 2008, 2015, 'pause', NULL),
  ('Mobile Safari', '', 'Default web browser for iOS', 'Mobile Safari', '$regex$(?=.*(?:iPhone|iPad|iPod))(?=.*Safari/)(?!.*(?:CriOS|FxiOS|EdgiOS|OPiOS|DuckDuckGo|Instagram|FBAV))', '', '', 2007, 0, 'active', NULL),
  ('Yandex Browser', '', 'Yandex Browser; calendar-based numbering follows 1.x, for example 13.10 (2013-10)', 'Yandex Browser', '$regex$YaBrowser', '', '', 2012, 0, 'active', NULL),
  ('Microsoft Edge', '', 'Microsoft''s modern web browser', 'Edge', '$regex$Edg', '', '', 2015, 0, 'active', NULL),
  ('Chromium', '', 'Open-source web browser project by Google', 'Chromium', '$regex$Chromium', '', '', 2008, 0, 'active', NULL),
  ('Brave', '', 'Brave Browser; usually identifies as Chrome in the User-Agent header; detection requires Client Hints or navigator.brave', 'Brave', '$regex$Brave', '', '', 2016, 0, 'active', NULL),
  ('UC Browser', '', 'Web browser developed by UCWeb, a subsidiary of Alibaba Group', 'UC Browser', '$regex$UCBrowser', '', '', 2004, 0, 'active', NULL),
  ('Vivaldi', '', 'A privacy-focused web browser developed by Vivaldi Technologies', 'Vivaldi', '$regex$Vivaldi', '', '', 2016, 0, 'active', NULL),
  ('Opera', '', 'Opera web browser', 'Opera', '$regex$OPR/|Opera/', '', '', 1996, 0, 'active', NULL),
  ('Opera Mini', '', 'Opera Mini mobile browser', 'Opera Mini', '$regex$Opera Mini', '', '', 2005, 0, 'active', NULL),
  ('Samsung Internet', '', 'Samsung Internet Browser', 'Samsung Internet', '$regex$SamsungBrowser', '', '', 2013, 0, 'active', NULL),
  ('Android WebView', '', 'Android System WebView', 'Android WebView', '$regex$; wv\)', '', '', 2014, 0, 'active', NULL),
  ('Amazon Silk', '', 'Amazon Silk browser; the product version is distinct from the Chromium/Chrome version; release years must not be copied automatically', 'Amazon Silk', '$regex$Silk/', '', '', 2011, 0, 'active', NULL),
  ('Huawei Browser', '', 'Huawei Browser', 'Huawei Browser', '$regex$HuaweiBrowser', '', '', 2019, 0, 'active', NULL),
  ('MIUI Browser', '', 'Xiaomi MIUI Browser', 'MIUI Browser', '$regex$MiuiBrowser|XiaoMi', '', '', 2014, 0, 'active', NULL),
  ('QQ Browser', '', 'Tencent QQ Browser', 'QQ Browser', '$regex$MQQBrowser|QQBrowser', '', '', 2010, 0, 'active', NULL),
  ('Naver Whale', '', 'Naver Whale browser', 'Whale', '$regex$Whale/', '', '', 2017, 0, 'active', NULL),
  ('DuckDuckGo', '', 'DuckDuckGo Privacy Browser', 'DuckDuckGo', '$regex$DuckDuckGo|Ddg/', '', '', 2018, 0, 'active', NULL),
  ('Facebook', '', 'Facebook in-app browser; application version, not a separate browser engine version', 'Facebook', '$regex$FBAN|FBAV|FB_IAB', '', '', 2012, 0, 'active', NULL),
  ('Instagram', '', 'Instagram in-app browser; application version, not a separate browser engine version', 'Instagram', '$regex$Instagram', '', '', 2013, 0, 'active', NULL),
  ('Chrome iOS', '', 'Google Chrome for iOS', 'Chrome iOS', '$regex$CriOS', '', '', 2012, 0, 'active', NULL),
  ('Firefox iOS', '', 'Mozilla Firefox for iOS', 'Firefox iOS', '$regex$FxiOS', '', '', 2015, 0, 'active', NULL),
  ('Coc Coc', '', 'Coc Coc browser (Vietnam); the product version is distinct from the Chromium/Chrome version; release years must not be copied automatically', 'Coc Coc', '$regex$coc_coc_browser', '', '', 2013, 0, 'active', NULL)
ON CONFLICT (name) DO UPDATE SET
    version = EXCLUDED.version,
    description = EXCLUDED.description,
    match_name_exp = EXCLUDED.match_name_exp,
    match_ua_exp = EXCLUDED.match_ua_exp,
    match_ver_min_exp = EXCLUDED.match_ver_min_exp,
    match_ver_max_exp = EXCLUDED.match_ver_max_exp,
    year_release = EXCLUDED.year_release,
    year_end_support = EXCLUDED.year_end_support,
    active = EXCLUDED.active,
    parent_id = EXCLUDED.parent_id,
    updated_at = NOW();

-- Versions of Internet Explorer
INSERT INTO type_browser (name, version, description, match_name_exp, match_ua_exp, match_ver_min_exp, match_ver_max_exp, year_release, year_end_support, active, parent_id)
VALUES
  ('IE 1', '1.0', 'Internet Explorer 1.0', 'IE 1', '$regex$MSIE 1(\.|[ ;])', '1.0', '2.0', 1995, 1996, 'pause', (SELECT id FROM type_browser WHERE name = 'Internet Explorer' LIMIT 1)),
  ('IE 2', '2.0', 'Internet Explorer 2.0', 'IE 2', '$regex$MSIE 2(\.|[ ;])', '2.0', '3.0', 1995, 1997, 'pause', (SELECT id FROM type_browser WHERE name = 'Internet Explorer' LIMIT 1)),
  ('IE 3', '3.0', 'Internet Explorer 3.0', 'IE 3', '$regex$MSIE 3(\.|[ ;])', '3.0', '4.0', 1996, 2001, 'pause', (SELECT id FROM type_browser WHERE name = 'Internet Explorer' LIMIT 1)),
  ('IE 4', '4.0', 'Internet Explorer 4.0', 'IE 4', '$regex$MSIE 4(\.|[ ;])', '4.0', '5.0', 1997, 2006, 'pause', (SELECT id FROM type_browser WHERE name = 'Internet Explorer' LIMIT 1)),
  ('IE 5', '5.0', 'Internet Explorer: all 5.x versions; range [5.0, 6.0)', 'IE 5', '$regex$MSIE 5(\.|[ ;])', '5.0', '6.0', 1999, 2010, 'pause', (SELECT id FROM type_browser WHERE name = 'Internet Explorer' LIMIT 1)),
  ('IE 6', '6.0', 'Internet Explorer 6.0', 'IE 6', '$regex$MSIE 6(\.|[ ;])', '6.0', '7.0', 2001, 2014, 'pause', (SELECT id FROM type_browser WHERE name = 'Internet Explorer' LIMIT 1)),
  ('IE 7', '7.0', 'Internet Explorer 7.0', 'IE 7', '$regex$MSIE 7(\.|[ ;])', '7.0', '8.0', 2006, 2016, 'pause', (SELECT id FROM type_browser WHERE name = 'Internet Explorer' LIMIT 1)),
  ('IE 8', '8.0', 'Internet Explorer 8.0', 'IE 8', '$regex$MSIE 8(\.|[ ;])', '8.0', '9.0', 2009, 2016, 'pause', (SELECT id FROM type_browser WHERE name = 'Internet Explorer' LIMIT 1)),
  ('IE 9', '9.0', 'Internet Explorer 9.0', 'IE 9', '$regex$MSIE 9(\.|[ ;])', '9.0', '10.0', 2011, 2020, 'pause', (SELECT id FROM type_browser WHERE name = 'Internet Explorer' LIMIT 1)),
  ('IE 10', '10.0', 'Internet Explorer 10.0', 'IE 10', '$regex$MSIE 10(\.|[ ;])', '10.0', '11.0', 2012, 2020, 'pause', (SELECT id FROM type_browser WHERE name = 'Internet Explorer' LIMIT 1)),
  ('IE 11', '11.0', 'Internet Explorer 11.0', 'IE 11', '$regex$Trident/7\.0.*rv:11\.0|MSIE 11(\.|[ ;])', '11.0', '12.0', 2013, 2022, 'pause', (SELECT id FROM type_browser WHERE name = 'Internet Explorer' LIMIT 1))
ON CONFLICT (name) DO UPDATE SET
    version = EXCLUDED.version,
    description = EXCLUDED.description,
    match_name_exp = EXCLUDED.match_name_exp,
    match_ua_exp = EXCLUDED.match_ua_exp,
    match_ver_min_exp = EXCLUDED.match_ver_min_exp,
    match_ver_max_exp = EXCLUDED.match_ver_max_exp,
    year_release = EXCLUDED.year_release,
    year_end_support = EXCLUDED.year_end_support,
    active = EXCLUDED.active,
    parent_id = EXCLUDED.parent_id,
    updated_at = NOW();

-- Versions of Mozilla Firefox
INSERT INTO type_browser (name, version, description, match_name_exp, match_ua_exp, match_ver_min_exp, match_ver_max_exp, year_release, year_end_support, active, parent_id)
VALUES
  ('Firefox 1', '1.0', 'Mozilla Firefox: versions 1–9; range [1.0, 10.0)', 'Firefox 1', '$regex$Firefox/[1-9](\.|$)', '1.0', '10.0', 2004, 2012, 'pause', (SELECT id FROM type_browser WHERE name = 'Mozilla Firefox' LIMIT 1)),
  ('Firefox 10', '10.0', 'Mozilla Firefox: versions 10–19; range [10.0, 20.0)', 'Firefox 10', '$regex$Firefox/1[0-9](\.|$)', '10.0', '20.0', 2012, 2013, 'pause', (SELECT id FROM type_browser WHERE name = 'Mozilla Firefox' LIMIT 1)),
  ('Firefox 20', '20.0', 'Mozilla Firefox: versions 20–29; range [20.0, 30.0)', 'Firefox 20', '$regex$Firefox/2[0-9](\.|$)', '20.0', '30.0', 2013, 2014, 'pause', (SELECT id FROM type_browser WHERE name = 'Mozilla Firefox' LIMIT 1)),
  ('Firefox 30', '30.0', 'Mozilla Firefox: versions 30–39; range [30.0, 40.0)', 'Firefox 30', '$regex$Firefox/3[0-9](\.|$)', '30.0', '40.0', 2014, 2016, 'pause', (SELECT id FROM type_browser WHERE name = 'Mozilla Firefox' LIMIT 1)),
  ('Firefox 40', '40.0', 'Mozilla Firefox: versions 40–49; range [40.0, 50.0)', 'Firefox 40', '$regex$Firefox/4[0-9](\.|$)', '40.0', '50.0', 2015, 2017, 'pause', (SELECT id FROM type_browser WHERE name = 'Mozilla Firefox' LIMIT 1)),
  ('Firefox 50', '50.0', 'Mozilla Firefox: versions 50–59; range [50.0, 60.0)', 'Firefox 50', '$regex$Firefox/5[0-9](\.|$)', '50.0', '60.0', 2016, 2018, 'pause', (SELECT id FROM type_browser WHERE name = 'Mozilla Firefox' LIMIT 1)),
  ('Firefox 60', '60.0', 'Mozilla Firefox: versions 60–69; range [60.0, 70.0)', 'Firefox 60', '$regex$Firefox/6[0-9](\.|$)', '60.0', '70.0', 2018, 2020, 'pause', (SELECT id FROM type_browser WHERE name = 'Mozilla Firefox' LIMIT 1)),
  ('Firefox 70', '70.0', 'Mozilla Firefox: versions 70–79; range [70.0, 80.0)', 'Firefox 70', '$regex$Firefox/7[0-9](\.|$)', '70.0', '80.0', 2019, 2021, 'pause', (SELECT id FROM type_browser WHERE name = 'Mozilla Firefox' LIMIT 1)),
  ('Firefox 80', '80.0', 'Mozilla Firefox: versions 80–89; range [80.0, 90.0)', 'Firefox 80', '$regex$Firefox/8[0-9](\.|$)', '80.0', '90.0', 2020, 2021, 'pause', (SELECT id FROM type_browser WHERE name = 'Mozilla Firefox' LIMIT 1)),
  ('Firefox 90', '90.0', 'Mozilla Firefox: versions 90–99; range [90.0, 100.0)', 'Firefox 90', '$regex$Firefox/9[0-9](\.|$)', '90.0', '100.0', 2021, 2022, 'pause', (SELECT id FROM type_browser WHERE name = 'Mozilla Firefox' LIMIT 1)),
  ('Firefox 100', '100.0', 'Mozilla Firefox: versions 100–109; range [100.0, 110.0)', 'Firefox 100', '$regex$Firefox/10[0-9](\.|$)', '100.0', '110.0', 2022, 2023, 'pause', (SELECT id FROM type_browser WHERE name = 'Mozilla Firefox' LIMIT 1)),
  ('Firefox 110', '110.0', 'Mozilla Firefox: versions 110–119; range [110.0, 120.0)', 'Firefox 110', '$regex$Firefox/11[0-9](\.|$)', '110.0', '120.0', 2023, 0, 'active', (SELECT id FROM type_browser WHERE name = 'Mozilla Firefox' LIMIT 1)),
  ('Firefox 120', '120.0', 'Mozilla Firefox: versions 120–129; range [120.0, 130.0)', 'Firefox 120', '$regex$Firefox/12[0-9](\.|$)', '120.0', '130.0', 2023, 2025, 'pause', (SELECT id FROM type_browser WHERE name = 'Mozilla Firefox' LIMIT 1)),
  ('Firefox 130', '130.0', 'Mozilla Firefox: versions 130–139; range [130.0, 140.0)', 'Firefox 130', '$regex$Firefox/13[0-9](\.|$)', '130.0', '140.0', 2024, 2025, 'active', (SELECT id FROM type_browser WHERE name = 'Mozilla Firefox' LIMIT 1)),
  ('Firefox 140', '140.0', 'Mozilla Firefox: versions 140–149; range [140.0, 150.0)', 'Firefox 140', '$regex$Firefox/14[0-9](\.|$)', '140.0', '150.0', 2025, 0, 'active', (SELECT id FROM type_browser WHERE name = 'Mozilla Firefox' LIMIT 1)),
  ('Firefox 150', '150.0', 'Mozilla Firefox: versions 150–159; range [150.0, 160.0)', 'Firefox 150', '$regex$Firefox/15[0-9](\.|$)', '150.0', '160.0', 2026, 0, 'active', (SELECT id FROM type_browser WHERE name = 'Mozilla Firefox' LIMIT 1))
ON CONFLICT (name) DO UPDATE SET
    version = EXCLUDED.version,
    description = EXCLUDED.description,
    match_name_exp = EXCLUDED.match_name_exp,
    match_ua_exp = EXCLUDED.match_ua_exp,
    match_ver_min_exp = EXCLUDED.match_ver_min_exp,
    match_ver_max_exp = EXCLUDED.match_ver_max_exp,
    year_release = EXCLUDED.year_release,
    year_end_support = EXCLUDED.year_end_support,
    active = EXCLUDED.active,
    parent_id = EXCLUDED.parent_id,
    updated_at = NOW();

-- Versions of Google Chrome
INSERT INTO type_browser (name, version, description, match_name_exp, match_ua_exp, match_ver_min_exp, match_ver_max_exp, year_release, year_end_support, active, parent_id)
VALUES
  ('Chrome 1', '1.0', 'Google Chrome: versions 1–9; range [1.0, 10.0)', 'Chrome 1', '$regex$Chrome/[1-9](\.|$)', '1.0', '10.0', 2008, 2013, 'pause', (SELECT id FROM type_browser WHERE name = 'Google Chrome' LIMIT 1)),
  ('Chrome 10', '10.0', 'Google Chrome: versions 10–19; range [10.0, 20.0)', 'Chrome 10', '$regex$Chrome/1[0-9](\.|$)', '10.0', '20.0', 2011, 2013, 'pause', (SELECT id FROM type_browser WHERE name = 'Google Chrome' LIMIT 1)),
  ('Chrome 20', '20.0', 'Google Chrome: versions 20–29; range [20.0, 30.0)', 'Chrome 20', '$regex$Chrome/2[0-9](\.|$)', '20.0', '30.0', 2012, 2013, 'pause', (SELECT id FROM type_browser WHERE name = 'Google Chrome' LIMIT 1)),
  ('Chrome 30', '30.0', 'Google Chrome: versions 30–39; range [30.0, 40.0)', 'Chrome 30', '$regex$Chrome/3[0-9](\.|$)', '30.0', '40.0', 2013, 2015, 'pause', (SELECT id FROM type_browser WHERE name = 'Google Chrome' LIMIT 1)),
  ('Chrome 40', '40.0', 'Google Chrome: versions 40–49; range [40.0, 50.0)', 'Chrome 40', '$regex$Chrome/4[0-9](\.|$)', '40.0', '50.0', 2015, 2016, 'pause', (SELECT id FROM type_browser WHERE name = 'Google Chrome' LIMIT 1)),
  ('Chrome 50', '50.0', 'Google Chrome: versions 50–59; range [50.0, 60.0)', 'Chrome 50', '$regex$Chrome/5[0-9](\.|$)', '50.0', '60.0', 2016, 2017, 'pause', (SELECT id FROM type_browser WHERE name = 'Google Chrome' LIMIT 1)),
  ('Chrome 60', '60.0', 'Google Chrome: versions 60–69; range [60.0, 70.0)', 'Chrome 60', '$regex$Chrome/6[0-9](\.|$)', '60.0', '70.0', 2017, 2018, 'pause', (SELECT id FROM type_browser WHERE name = 'Google Chrome' LIMIT 1)),
  ('Chrome 70', '70.0', 'Google Chrome: versions 70–79; range [70.0, 80.0)', 'Chrome 70', '$regex$Chrome/7[0-9](\.|$)', '70.0', '80.0', 2018, 2020, 'pause', (SELECT id FROM type_browser WHERE name = 'Google Chrome' LIMIT 1)),
  ('Chrome 80', '80.0', 'Google Chrome: versions 80–89; range [80.0, 90.0)', 'Chrome 80', '$regex$Chrome/8[0-9](\.|$)', '80.0', '90.0', 2020, 2021, 'pause', (SELECT id FROM type_browser WHERE name = 'Google Chrome' LIMIT 1)),
  ('Chrome 90', '90.0', 'Google Chrome: versions 90–99; range [90.0, 100.0)', 'Chrome 90', '$regex$Chrome/9[0-9](\.|$)', '90.0', '100.0', 2021, 2022, 'pause', (SELECT id FROM type_browser WHERE name = 'Google Chrome' LIMIT 1)),
  ('Chrome 100', '100.0', 'Google Chrome: versions 100–109; range [100.0, 110.0)', 'Chrome 100', '$regex$Chrome/10[0-9](\.|$)', '100.0', '110.0', 2022, 2023, 'pause', (SELECT id FROM type_browser WHERE name = 'Google Chrome' LIMIT 1)),
  ('Chrome 110', '110.0', 'Google Chrome: versions 110–119; range [110.0, 120.0)', 'Chrome 110', '$regex$Chrome/11[0-9](\.|$)', '110.0', '120.0', 2023, 2023, 'pause', (SELECT id FROM type_browser WHERE name = 'Google Chrome' LIMIT 1)),
  ('Chrome 120', '120.0', 'Google Chrome: versions 120–129; range [120.0, 130.0)', 'Chrome 120', '$regex$Chrome/12[0-9](\.|$)', '120.0', '130.0', 2023, 2024, 'pause', (SELECT id FROM type_browser WHERE name = 'Google Chrome' LIMIT 1)),
  ('Chrome 130', '130.0', 'Google Chrome: versions 130–139; range [130.0, 140.0)', 'Chrome 130', '$regex$Chrome/13[0-9](\.|$)', '130.0', '140.0', 2024, 2025, 'active', (SELECT id FROM type_browser WHERE name = 'Google Chrome' LIMIT 1)),
  ('Chrome 140', '140.0', 'Google Chrome: versions 140–149; range [140.0, 150.0)', 'Chrome 140', '$regex$Chrome/14[0-9](\.|$)', '140.0', '150.0', 2025, 2026, 'active', (SELECT id FROM type_browser WHERE name = 'Google Chrome' LIMIT 1)),
  ('Chrome 150', '150.0', 'Google Chrome: versions 150–159; range [150.0, 160.0)', 'Chrome 150', '$regex$Chrome/15[0-9](\.|$)', '150.0', '160.0', 2026, 0, 'active', (SELECT id FROM type_browser WHERE name = 'Google Chrome' LIMIT 1))
ON CONFLICT (name) DO UPDATE SET
    version = EXCLUDED.version,
    description = EXCLUDED.description,
    match_name_exp = EXCLUDED.match_name_exp,
    match_ua_exp = EXCLUDED.match_ua_exp,
    match_ver_min_exp = EXCLUDED.match_ver_min_exp,
    match_ver_max_exp = EXCLUDED.match_ver_max_exp,
    year_release = EXCLUDED.year_release,
    year_end_support = EXCLUDED.year_end_support,
    active = EXCLUDED.active,
    parent_id = EXCLUDED.parent_id,
    updated_at = NOW();

-- Versions of Safari
INSERT INTO type_browser (name, version, description, match_name_exp, match_ua_exp, match_ver_min_exp, match_ver_max_exp, year_release, year_end_support, active, parent_id)
VALUES
  ('Safari 1', '1.0', 'Safari: all 1.x versions; range [1.0, 2.0)', 'Safari 1', '$regex$Version/1(\.|$)', '1.0', '2.0', 2003, 2008, 'pause', (SELECT id FROM type_browser WHERE name = 'Safari' LIMIT 1)),
  ('Safari 2', '2.0', 'Safari 2.0', 'Safari 2', '$regex$Version/2(\.|$)', '2.0', '3.0', 2005, 2008, 'pause', (SELECT id FROM type_browser WHERE name = 'Safari' LIMIT 1)),
  ('Safari 3', '3.0', 'Safari: all 3.x versions; range [3.0, 4.0)', 'Safari 3', '$regex$Version/3(\.|$)', '3.0', '4.0', 2007, 2011, 'pause', (SELECT id FROM type_browser WHERE name = 'Safari' LIMIT 1)),
  ('Safari 4', '4.0', 'Safari 4.0', 'Safari 4', '$regex$Version/4(\.|$)', '4.0', '5.0', 2009, 2012, 'pause', (SELECT id FROM type_browser WHERE name = 'Safari' LIMIT 1)),
  ('Safari 5', '5.0', 'Safari: all 5.x versions; range [5.0, 6.0)', 'Safari 5', '$regex$Version/5(\.|$)', '5.0', '6.0', 2010, 2014, 'pause', (SELECT id FROM type_browser WHERE name = 'Safari' LIMIT 1)),
  ('Safari 6', '6.0', 'Safari 6.0', 'Safari 6', '$regex$Version/6(\.|$)', '6.0', '7.0', 2012, 2015, 'pause', (SELECT id FROM type_browser WHERE name = 'Safari' LIMIT 1)),
  ('Safari 7', '7.0', 'Safari 7.0', 'Safari 7', '$regex$Version/7(\.|$)', '7.0', '8.0', 2013, 2016, 'pause', (SELECT id FROM type_browser WHERE name = 'Safari' LIMIT 1)),
  ('Safari 8', '8.0', 'Safari 8.0', 'Safari 8', '$regex$Version/8(\.|$)', '8.0', '9.0', 2014, 2017, 'pause', (SELECT id FROM type_browser WHERE name = 'Safari' LIMIT 1)),
  ('Safari 9', '9.0', 'Safari: all 9.x versions; range [9.0, 10.0)', 'Safari 9', '$regex$Version/9(\.|$)', '9.0', '10.0', 2015, 2019, 'pause', (SELECT id FROM type_browser WHERE name = 'Safari' LIMIT 1)),
  ('Safari 10', '10.0', 'Safari: all 10.x versions; range [10.0, 11.0)', 'Safari 10', '$regex$Version/10(\.|$)', '10.0', '11.0', 2016, 2020, 'pause', (SELECT id FROM type_browser WHERE name = 'Safari' LIMIT 1)),
  ('Safari 11', '11.0', 'Safari: all 11.x versions; range [11.0, 12.0)', 'Safari 11', '$regex$Version/11(\.|$)', '11.0', '12.0', 2017, 2021, 'pause', (SELECT id FROM type_browser WHERE name = 'Safari' LIMIT 1)),
  ('Safari 12', '12.0', 'Safari: all 12.x versions; range [12.0, 13.0)', 'Safari 12', '$regex$Version/12(\.|$)', '12.0', '13.0', 2018, 2022, 'pause', (SELECT id FROM type_browser WHERE name = 'Safari' LIMIT 1)),
  ('Safari 13', '13.0', 'Safari: all 13.x versions; range [13.0, 14.0)', 'Safari 13', '$regex$Version/13(\.|$)', '13.0', '14.0', 2019, 2023, 'pause', (SELECT id FROM type_browser WHERE name = 'Safari' LIMIT 1)),
  ('Safari 14', '14.0', 'Safari: all 14.x versions; range [14.0, 15.0)', 'Safari 14', '$regex$Version/14(\.|$)', '14.0', '15.0', 2020, 2024, 'pause', (SELECT id FROM type_browser WHERE name = 'Safari' LIMIT 1)),
  ('Safari 15', '15.0', 'Safari: all 15.x versions; range [15.0, 16.0)', 'Safari 15', '$regex$Version/15(\.|$)', '15.0', '16.0', 2021, 2025, 'pause', (SELECT id FROM type_browser WHERE name = 'Safari' LIMIT 1)),
  ('Safari 16', '16.0', 'Safari: all 16.x versions; range [16.0, 17.0)', 'Safari 16', '$regex$Version/16(\.|$)', '16.0', '17.0', 2022, 2025, 'pause', (SELECT id FROM type_browser WHERE name = 'Safari' LIMIT 1)),
  ('Safari 17', '17.0', 'Safari: all 17.x versions; range [17.0, 18.0)', 'Safari 17', '$regex$Version/17(\.|$)', '17.0', '18.0', 2023, 2024, 'pause', (SELECT id FROM type_browser WHERE name = 'Safari' LIMIT 1)),
  ('Safari 18', '18.0', 'Safari: all 18.x versions; range [18.0, 19.0)', 'Safari 18', '$regex$Version/18(\.|$)', '18.0', '19.0', 2024, 2025, 'active', (SELECT id FROM type_browser WHERE name = 'Safari' LIMIT 1)),
  ('Safari 26', '26.0', 'Safari: all 26.x versions; range [26.0, 27.0)', 'Safari 26', '$regex$Version/26(\.|$)', '26.0', '27.0', 2025, 2026, 'active', (SELECT id FROM type_browser WHERE name = 'Safari' LIMIT 1)),
  ('Safari 27', '27.0', 'Safari 27.0', 'Safari 27', '$regex$Version/27(\.|$)', '27.0', '28.0', 2026, 0, 'active', (SELECT id FROM type_browser WHERE name = 'Safari' LIMIT 1))
ON CONFLICT (name) DO UPDATE SET
    version = EXCLUDED.version,
    description = EXCLUDED.description,
    match_name_exp = EXCLUDED.match_name_exp,
    match_ua_exp = EXCLUDED.match_ua_exp,
    match_ver_min_exp = EXCLUDED.match_ver_min_exp,
    match_ver_max_exp = EXCLUDED.match_ver_max_exp,
    year_release = EXCLUDED.year_release,
    year_end_support = EXCLUDED.year_end_support,
    active = EXCLUDED.active,
    parent_id = EXCLUDED.parent_id,
    updated_at = NOW();

-- Versions of Mobile Safari
INSERT INTO type_browser (name, version, description, match_name_exp, match_ua_exp, match_ver_min_exp, match_ver_max_exp, year_release, year_end_support, active, parent_id)
VALUES
  ('Mobile Safari 3', '3.0', 'Mobile Safari 3.0', 'Mobile Safari 3', '$regex$Version/3(\.|$).*Mobile.*Safari/', '3.0', '4.0', 2007, 2010, 'pause', (SELECT id FROM type_browser WHERE name = 'Mobile Safari' LIMIT 1)),
  ('Mobile Safari 4', '4.0', 'Mobile Safari 4.0', 'Mobile Safari 4', '$regex$Version/4(\.|$).*Mobile.*Safari/', '4.0', '5.0', 2009, 2012, 'pause', (SELECT id FROM type_browser WHERE name = 'Mobile Safari' LIMIT 1)),
  ('Mobile Safari 5', '5.0', 'Mobile Safari 5.0', 'Mobile Safari 5', '$regex$Version/5(\.|$).*Mobile.*Safari/', '5.0', '6.0', 2010, 2013, 'pause', (SELECT id FROM type_browser WHERE name = 'Mobile Safari' LIMIT 1)),
  ('Mobile Safari 6', '6.0', 'Mobile Safari 6.0', 'Mobile Safari 6', '$regex$Version/6(\.|$).*Mobile.*Safari/', '6.0', '7.0', 2012, 2015, 'pause', (SELECT id FROM type_browser WHERE name = 'Mobile Safari' LIMIT 1)),
  ('Mobile Safari 7', '7.0', 'Mobile Safari 7.0', 'Mobile Safari 7', '$regex$Version/7(\.|$).*Mobile.*Safari/', '7.0', '8.0', 2013, 2016, 'pause', (SELECT id FROM type_browser WHERE name = 'Mobile Safari' LIMIT 1)),
  ('Mobile Safari 8', '8.0', 'Mobile Safari 8.0', 'Mobile Safari 8', '$regex$Version/8(\.|$).*Mobile.*Safari/', '8.0', '9.0', 2014, 2017, 'pause', (SELECT id FROM type_browser WHERE name = 'Mobile Safari' LIMIT 1)),
  ('Mobile Safari 9', '9.0', 'Mobile Safari: all 9.x versions; range [9.0, 10.0)', 'Mobile Safari 9', '$regex$Version/9(\.|$).*Mobile.*Safari/', '9.0', '10.0', 2015, 2019, 'pause', (SELECT id FROM type_browser WHERE name = 'Mobile Safari' LIMIT 1)),
  ('Mobile Safari 10', '10.0', 'Mobile Safari: all 10.x versions; range [10.0, 11.0)', 'Mobile Safari 10', '$regex$Version/10(\.|$).*Mobile.*Safari/', '10.0', '11.0', 2016, 2020, 'pause', (SELECT id FROM type_browser WHERE name = 'Mobile Safari' LIMIT 1)),
  ('Mobile Safari 11', '11.0', 'Mobile Safari: all 11.x versions; range [11.0, 12.0)', 'Mobile Safari 11', '$regex$Version/11(\.|$).*Mobile.*Safari/', '11.0', '12.0', 2017, 2021, 'pause', (SELECT id FROM type_browser WHERE name = 'Mobile Safari' LIMIT 1)),
  ('Mobile Safari 12', '12.0', 'Mobile Safari: all 12.x versions; range [12.0, 13.0)', 'Mobile Safari 12', '$regex$Version/12(\.|$).*Mobile.*Safari/', '12.0', '13.0', 2018, 2022, 'pause', (SELECT id FROM type_browser WHERE name = 'Mobile Safari' LIMIT 1)),
  ('Mobile Safari 13', '13.0', 'Mobile Safari: all 13.x versions; range [13.0, 14.0)', 'Mobile Safari 13', '$regex$Version/13(\.|$).*Mobile.*Safari/', '13.0', '14.0', 2019, 2023, 'pause', (SELECT id FROM type_browser WHERE name = 'Mobile Safari' LIMIT 1)),
  ('Mobile Safari 14', '14.0', 'Mobile Safari: all 14.x versions; range [14.0, 15.0)', 'Mobile Safari 14', '$regex$Version/14(\.|$).*Mobile.*Safari/', '14.0', '15.0', 2020, 2024, 'pause', (SELECT id FROM type_browser WHERE name = 'Mobile Safari' LIMIT 1)),
  ('Mobile Safari 15', '15.0', 'Mobile Safari: all 15.x versions; range [15.0, 16.0)', 'Mobile Safari 15', '$regex$Version/15(\.|$).*Mobile.*Safari/', '15.0', '16.0', 2021, 2025, 'pause', (SELECT id FROM type_browser WHERE name = 'Mobile Safari' LIMIT 1)),
  ('Mobile Safari 16', '16.0', 'Mobile Safari: all 16.x versions; range [16.0, 17.0)', 'Mobile Safari 16', '$regex$Version/16(\.|$).*Mobile.*Safari/', '16.0', '17.0', 2022, 2025, 'pause', (SELECT id FROM type_browser WHERE name = 'Mobile Safari' LIMIT 1)),
  ('Mobile Safari 17', '17.0', 'Mobile Safari: all 17.x versions; range [17.0, 18.0)', 'Mobile Safari 17', '$regex$Version/17(\.|$).*Mobile.*Safari/', '17.0', '18.0', 2023, 2024, 'pause', (SELECT id FROM type_browser WHERE name = 'Mobile Safari' LIMIT 1)),
  ('Mobile Safari 18', '18.0', 'Mobile Safari: all 18.x versions; range [18.0, 19.0)', 'Mobile Safari 18', '$regex$Version/18(\.|$).*Mobile.*Safari/', '18.0', '19.0', 2024, 2025, 'active', (SELECT id FROM type_browser WHERE name = 'Mobile Safari' LIMIT 1)),
  ('Mobile Safari 26', '26.0', 'Mobile Safari: all 26.x versions; range [26.0, 27.0)', 'Mobile Safari 26', '$regex$Version/26(\.|$).*Mobile.*Safari/', '26.0', '27.0', 2025, 2026, 'active', (SELECT id FROM type_browser WHERE name = 'Mobile Safari' LIMIT 1)),
  ('Mobile Safari 27', '27.0', 'Mobile Safari 27.0', 'Mobile Safari 27', '$regex$Version/27(\.|$).*Mobile.*Safari/', '27.0', '28.0', 2026, 0, 'active', (SELECT id FROM type_browser WHERE name = 'Mobile Safari' LIMIT 1))
ON CONFLICT (name) DO UPDATE SET
    version = EXCLUDED.version,
    description = EXCLUDED.description,
    match_name_exp = EXCLUDED.match_name_exp,
    match_ua_exp = EXCLUDED.match_ua_exp,
    match_ver_min_exp = EXCLUDED.match_ver_min_exp,
    match_ver_max_exp = EXCLUDED.match_ver_max_exp,
    year_release = EXCLUDED.year_release,
    year_end_support = EXCLUDED.year_end_support,
    active = EXCLUDED.active,
    parent_id = EXCLUDED.parent_id,
    updated_at = NOW();

-- Versions of Yandex Browser
INSERT INTO type_browser (name, version, description, match_name_exp, match_ua_exp, match_ver_min_exp, match_ver_max_exp, year_release, year_end_support, active, parent_id)
VALUES
  ('Yandex Browser 1', '1.0', 'Yandex Browser 1', 'Yandex Browser 1', '$regex$YaBrowser/1(\.|$)', '1.0', '2.0', 2012, 2015, 'pause', (SELECT id FROM type_browser WHERE name = 'Yandex Browser' LIMIT 1)),
  ('Yandex Browser 13', '13.0', 'Yandex Browser: all 13.x versions; range [13.0, 14.0)', 'Yandex Browser 13', '$regex$YaBrowser/13(\.|$)', '13.0', '14.0', 2013, 2016, 'pause', (SELECT id FROM type_browser WHERE name = 'Yandex Browser' LIMIT 1)),
  ('Yandex Browser 14', '14.0', 'Yandex Browser 14; calendar-based user-agent group; does not imply an exact release 14.0', 'Yandex Browser 14', '$regex$YaBrowser/14(\.|$)', '14.0', '15.0', 2014, 2017, 'pause', (SELECT id FROM type_browser WHERE name = 'Yandex Browser' LIMIT 1)),
  ('Yandex Browser 15', '15.0', 'Yandex Browser 15; calendar-based user-agent group; does not imply an exact release 15.0', 'Yandex Browser 15', '$regex$YaBrowser/15(\.|$)', '15.0', '16.0', 2015, 2018, 'pause', (SELECT id FROM type_browser WHERE name = 'Yandex Browser' LIMIT 1)),
  ('Yandex Browser 16', '16.0', 'Yandex Browser 16; calendar-based user-agent group; does not imply an exact release 16.0', 'Yandex Browser 16', '$regex$YaBrowser/16(\.|$)', '16.0', '17.0', 2016, 2019, 'pause', (SELECT id FROM type_browser WHERE name = 'Yandex Browser' LIMIT 1)),
  ('Yandex Browser 17', '17.0', 'Yandex Browser 17; calendar-based user-agent group; does not imply an exact release 17.0', 'Yandex Browser 17', '$regex$YaBrowser/17(\.|$)', '17.0', '18.0', 2017, 2020, 'pause', (SELECT id FROM type_browser WHERE name = 'Yandex Browser' LIMIT 1)),
  ('Yandex Browser 18', '18.0', 'Yandex Browser 18; calendar-based user-agent group; does not imply an exact release 18.0', 'Yandex Browser 18', '$regex$YaBrowser/18(\.|$)', '18.0', '19.0', 2018, 2021, 'pause', (SELECT id FROM type_browser WHERE name = 'Yandex Browser' LIMIT 1)),
  ('Yandex Browser 19', '19.0', 'Yandex Browser 19; calendar-based user-agent group; does not imply an exact release 19.0', 'Yandex Browser 19', '$regex$YaBrowser/19(\.|$)', '19.0', '20.0', 2019, 2022, 'pause', (SELECT id FROM type_browser WHERE name = 'Yandex Browser' LIMIT 1)),
  ('Yandex Browser 20', '20.0', 'Yandex Browser 20; calendar-based user-agent group; does not imply an exact release 20.0', 'Yandex Browser 20', '$regex$YaBrowser/20(\.|$)', '20.0', '21.0', 2020, 2023, 'pause', (SELECT id FROM type_browser WHERE name = 'Yandex Browser' LIMIT 1)),
  ('Yandex Browser 21', '21.0', 'Yandex Browser 21; calendar-based user-agent group; does not imply an exact release 21.0', 'Yandex Browser 21', '$regex$YaBrowser/21(\.|$)', '21.0', '22.0', 2021, 2024, 'pause', (SELECT id FROM type_browser WHERE name = 'Yandex Browser' LIMIT 1)),
  ('Yandex Browser 22', '22.0', 'Yandex Browser 22; calendar-based user-agent group; does not imply an exact release 22.0', 'Yandex Browser 22', '$regex$YaBrowser/22(\.|$)', '22.0', '23.0', 2022, 2025, 'pause', (SELECT id FROM type_browser WHERE name = 'Yandex Browser' LIMIT 1)),
  ('Yandex Browser 23', '23.0', 'Yandex Browser 23; calendar-based user-agent group; does not imply an exact release 23.0', 'Yandex Browser 23', '$regex$YaBrowser/23(\.|$)', '23.0', '24.0', 2023, 2024, 'pause', (SELECT id FROM type_browser WHERE name = 'Yandex Browser' LIMIT 1)),
  ('Yandex Browser 24', '24.0', 'Yandex Browser 24; calendar-based user-agent group; does not imply an exact release 24.0', 'Yandex Browser 24', '$regex$YaBrowser/24(\.|$)', '24.0', '25.0', 2024, 2025, 'active', (SELECT id FROM type_browser WHERE name = 'Yandex Browser' LIMIT 1)),
  ('Yandex Browser 25', '25.0', 'Yandex Browser 25; calendar-based user-agent group; does not imply an exact release 25.0', 'Yandex Browser 25', '$regex$YaBrowser/25(\.|$)', '25.0', '26.0', 2025, 0, 'active', (SELECT id FROM type_browser WHERE name = 'Yandex Browser' LIMIT 1))
ON CONFLICT (name) DO UPDATE SET
    version = EXCLUDED.version,
    description = EXCLUDED.description,
    match_name_exp = EXCLUDED.match_name_exp,
    match_ua_exp = EXCLUDED.match_ua_exp,
    match_ver_min_exp = EXCLUDED.match_ver_min_exp,
    match_ver_max_exp = EXCLUDED.match_ver_max_exp,
    year_release = EXCLUDED.year_release,
    year_end_support = EXCLUDED.year_end_support,
    active = EXCLUDED.active,
    parent_id = EXCLUDED.parent_id,
    updated_at = NOW();

-- Versions of Microsoft Edge
INSERT INTO type_browser (name, version, description, match_name_exp, match_ua_exp, match_ver_min_exp, match_ver_max_exp, year_release, year_end_support, active, parent_id)
VALUES
  ('Edge 10', '10.0', 'Microsoft Edge: versions 10–19; range [10.0, 20.0)', 'Edge 10', '$regex$Edge/1[0-9](\.|$)', '10.0', '20.0', 2015, 2021, 'pause', (SELECT id FROM type_browser WHERE name = 'Microsoft Edge' LIMIT 1)),
  ('Edge 70', '70.0', 'Microsoft Edge: versions 70–79; range [70.0, 80.0)', 'Edge 70', '$regex$(?:Edg|EdgA|EdgiOS)/7[0-9](\.|$)', '70.0', '80.0', 2020, 2023, 'pause', (SELECT id FROM type_browser WHERE name = 'Microsoft Edge' LIMIT 1)),
  ('Edge 80', '80.0', 'Microsoft Edge: versions 80–89; range [80.0, 90.0)', 'Edge 80', '$regex$(?:Edg|EdgA|EdgiOS)/8[0-9](\.|$)', '80.0', '90.0', 2020, 2024, 'pause', (SELECT id FROM type_browser WHERE name = 'Microsoft Edge' LIMIT 1)),
  ('Edge 90', '90.0', 'Microsoft Edge: versions 90–99; range [90.0, 100.0)', 'Edge 90', '$regex$(?:Edg|EdgA|EdgiOS)/9[0-9](\.|$)', '90.0', '100.0', 2021, 2025, 'pause', (SELECT id FROM type_browser WHERE name = 'Microsoft Edge' LIMIT 1)),
  ('Edge 100', '100.0', 'Microsoft Edge: versions 100–109; range [100.0, 110.0)', 'Edge 100', '$regex$(?:Edg|EdgA|EdgiOS)/10[0-9](\.|$)', '100.0', '110.0', 2022, 2025, 'pause', (SELECT id FROM type_browser WHERE name = 'Microsoft Edge' LIMIT 1)),
  ('Edge 110', '110.0', 'Microsoft Edge: versions 110–119; range [110.0, 120.0)', 'Edge 110', '$regex$(?:Edg|EdgA|EdgiOS)/11[0-9](\.|$)', '110.0', '120.0', 2023, 2023, 'pause', (SELECT id FROM type_browser WHERE name = 'Microsoft Edge' LIMIT 1)),
  ('Edge 120', '120.0', 'Microsoft Edge: versions 120–129; range [120.0, 130.0)', 'Edge 120', '$regex$(?:Edg|EdgA|EdgiOS)/12[0-9](\.|$)', '120.0', '130.0', 2023, 2024, 'pause', (SELECT id FROM type_browser WHERE name = 'Microsoft Edge' LIMIT 1)),
  ('Edge 130', '130.0', 'Microsoft Edge: versions 130–139; range [130.0, 140.0)', 'Edge 130', '$regex$(?:Edg|EdgA|EdgiOS)/13[0-9](\.|$)', '130.0', '140.0', 2024, 2025, 'active', (SELECT id FROM type_browser WHERE name = 'Microsoft Edge' LIMIT 1)),
  ('Edge 140', '140.0', 'Microsoft Edge: versions 140–149; range [140.0, 150.0)', 'Edge 140', '$regex$(?:Edg|EdgA|EdgiOS)/14[0-9](\.|$)', '140.0', '150.0', 2025, 2026, 'active', (SELECT id FROM type_browser WHERE name = 'Microsoft Edge' LIMIT 1)),
  ('Edge 150', '150.0', 'Microsoft Edge: versions 150–159; range [150.0, 160.0)', 'Edge 150', '$regex$(?:Edg|EdgA|EdgiOS)/15[0-9](\.|$)', '150.0', '160.0', 2026, 0, 'active', (SELECT id FROM type_browser WHERE name = 'Microsoft Edge' LIMIT 1))
ON CONFLICT (name) DO UPDATE SET
    version = EXCLUDED.version,
    description = EXCLUDED.description,
    match_name_exp = EXCLUDED.match_name_exp,
    match_ua_exp = EXCLUDED.match_ua_exp,
    match_ver_min_exp = EXCLUDED.match_ver_min_exp,
    match_ver_max_exp = EXCLUDED.match_ver_max_exp,
    year_release = EXCLUDED.year_release,
    year_end_support = EXCLUDED.year_end_support,
    active = EXCLUDED.active,
    parent_id = EXCLUDED.parent_id,
    updated_at = NOW();

-- Versions of Chromium
INSERT INTO type_browser (name, version, description, match_name_exp, match_ua_exp, match_ver_min_exp, match_ver_max_exp, year_release, year_end_support, active, parent_id)
VALUES
  ('Chromium 1', '1.0', 'Chromium: versions 1–9; range [1.0, 10.0)', 'Chromium 1', '$regex$Chromium/[1-9](\.|$)', '1.0', '10.0', 2008, 2011, 'pause', (SELECT id FROM type_browser WHERE name = 'Chromium' LIMIT 1)),
  ('Chromium 10', '10.0', 'Chromium: versions 10–19; range [10.0, 20.0)', 'Chromium 10', '$regex$Chromium/1[0-9](\.|$)', '10.0', '20.0', 2011, 2012, 'pause', (SELECT id FROM type_browser WHERE name = 'Chromium' LIMIT 1)),
  ('Chromium 20', '20.0', 'Chromium: versions 20–29; range [20.0, 30.0)', 'Chromium 20', '$regex$Chromium/2[0-9](\.|$)', '20.0', '30.0', 2012, 2013, 'pause', (SELECT id FROM type_browser WHERE name = 'Chromium' LIMIT 1)),
  ('Chromium 30', '30.0', 'Chromium: versions 30–39; range [30.0, 40.0)', 'Chromium 30', '$regex$Chromium/3[0-9](\.|$)', '30.0', '40.0', 2013, 2015, 'pause', (SELECT id FROM type_browser WHERE name = 'Chromium' LIMIT 1)),
  ('Chromium 40', '40.0', 'Chromium: versions 40–49; range [40.0, 50.0)', 'Chromium 40', '$regex$Chromium/4[0-9](\.|$)', '40.0', '50.0', 2015, 2016, 'pause', (SELECT id FROM type_browser WHERE name = 'Chromium' LIMIT 1)),
  ('Chromium 50', '50.0', 'Chromium: versions 50–59; range [50.0, 60.0)', 'Chromium 50', '$regex$Chromium/5[0-9](\.|$)', '50.0', '60.0', 2016, 2017, 'pause', (SELECT id FROM type_browser WHERE name = 'Chromium' LIMIT 1)),
  ('Chromium 60', '60.0', 'Chromium: versions 60–69; range [60.0, 70.0)', 'Chromium 60', '$regex$Chromium/6[0-9](\.|$)', '60.0', '70.0', 2017, 2018, 'pause', (SELECT id FROM type_browser WHERE name = 'Chromium' LIMIT 1)),
  ('Chromium 70', '70.0', 'Chromium: versions 70–79; range [70.0, 80.0)', 'Chromium 70', '$regex$Chromium/7[0-9](\.|$)', '70.0', '80.0', 2018, 2020, 'pause', (SELECT id FROM type_browser WHERE name = 'Chromium' LIMIT 1)),
  ('Chromium 80', '80.0', 'Chromium: versions 80–89; range [80.0, 90.0)', 'Chromium 80', '$regex$Chromium/8[0-9](\.|$)', '80.0', '90.0', 2020, 2021, 'pause', (SELECT id FROM type_browser WHERE name = 'Chromium' LIMIT 1)),
  ('Chromium 90', '90.0', 'Chromium: versions 90–99; range [90.0, 100.0)', 'Chromium 90', '$regex$Chromium/9[0-9](\.|$)', '90.0', '100.0', 2021, 2022, 'pause', (SELECT id FROM type_browser WHERE name = 'Chromium' LIMIT 1)),
  ('Chromium 100', '100.0', 'Chromium: versions 100–109; range [100.0, 110.0)', 'Chromium 100', '$regex$Chromium/10[0-9](\.|$)', '100.0', '110.0', 2022, 2023, 'pause', (SELECT id FROM type_browser WHERE name = 'Chromium' LIMIT 1)),
  ('Chromium 110', '110.0', 'Chromium: versions 110–119; range [110.0, 120.0)', 'Chromium 110', '$regex$Chromium/11[0-9](\.|$)', '110.0', '120.0', 2023, 2023, 'pause', (SELECT id FROM type_browser WHERE name = 'Chromium' LIMIT 1)),
  ('Chromium 120', '120.0', 'Chromium: versions 120–129; range [120.0, 130.0)', 'Chromium 120', '$regex$Chromium/12[0-9](\.|$)', '120.0', '130.0', 2023, 2024, 'pause', (SELECT id FROM type_browser WHERE name = 'Chromium' LIMIT 1)),
  ('Chromium 130', '130.0', 'Chromium: versions 130–139; range [130.0, 140.0)', 'Chromium 130', '$regex$Chromium/13[0-9](\.|$)', '130.0', '140.0', 2024, 2025, 'active', (SELECT id FROM type_browser WHERE name = 'Chromium' LIMIT 1)),
  ('Chromium 140', '140.0', 'Chromium: versions 140–149; range [140.0, 150.0)', 'Chromium 140', '$regex$Chromium/14[0-9](\.|$)', '140.0', '150.0', 2025, 2026, 'active', (SELECT id FROM type_browser WHERE name = 'Chromium' LIMIT 1)),
  ('Chromium 150', '150.0', 'Chromium: versions 150–159; range [150.0, 160.0)', 'Chromium 150', '$regex$Chromium/15[0-9](\.|$)', '150.0', '160.0', 2026, 0, 'active', (SELECT id FROM type_browser WHERE name = 'Chromium' LIMIT 1))
ON CONFLICT (name) DO UPDATE SET
    version = EXCLUDED.version,
    description = EXCLUDED.description,
    match_name_exp = EXCLUDED.match_name_exp,
    match_ua_exp = EXCLUDED.match_ua_exp,
    match_ver_min_exp = EXCLUDED.match_ver_min_exp,
    match_ver_max_exp = EXCLUDED.match_ver_max_exp,
    year_release = EXCLUDED.year_release,
    year_end_support = EXCLUDED.year_end_support,
    active = EXCLUDED.active,
    parent_id = EXCLUDED.parent_id,
    updated_at = NOW();

-- Versions of Brave
INSERT INTO type_browser (name, version, description, match_name_exp, match_ua_exp, match_ver_min_exp, match_ver_max_exp, year_release, year_end_support, active, parent_id)
VALUES
  ('Brave 1.0', '1.0', 'Brave 1.0', 'Brave 1.0', '$regex$Brave/1\.0(\.|$)', '1.0', '1.1', 2019, 2022, 'pause', (SELECT id FROM type_browser WHERE name = 'Brave' LIMIT 1)),
  ('Brave 1.10', '1.10', 'Brave 1.10', 'Brave 1.10', '$regex$Brave/1\.10(\.|$)', '1.10', '1.11', 2020, 2023, 'pause', (SELECT id FROM type_browser WHERE name = 'Brave' LIMIT 1)),
  ('Brave 1.20', '1.20', 'Brave 1.20', 'Brave 1.20', '$regex$Brave/1\.20(\.|$)', '1.20', '1.21', 2021, 2024, 'pause', (SELECT id FROM type_browser WHERE name = 'Brave' LIMIT 1)),
  ('Brave 1.30', '1.30', 'Brave 1.30', 'Brave 1.30', '$regex$Brave/1\.30(\.|$)', '1.30', '1.31', 2021, 2024, 'active', (SELECT id FROM type_browser WHERE name = 'Brave' LIMIT 1)),
  ('Brave 1.40', '1.40', 'Brave 1.40', 'Brave 1.40', '$regex$Brave/1\.40(\.|$)', '1.40', '1.41', 2022, 2025, 'active', (SELECT id FROM type_browser WHERE name = 'Brave' LIMIT 1)),
  ('Brave 1.50', '1.50', 'Brave 1.50', 'Brave 1.50', '$regex$Brave/1\.50(\.|$)', '1.50', '1.51', 2023, 2023, 'active', (SELECT id FROM type_browser WHERE name = 'Brave' LIMIT 1)),
  ('Brave 1.60', '1.60', 'Brave 1.60', 'Brave 1.60', '$regex$Brave/1\.60(\.|$)', '1.60', '1.61', 2023, 2024, 'active', (SELECT id FROM type_browser WHERE name = 'Brave' LIMIT 1)),
  ('Brave 1.70', '1.70', 'Brave 1.70', 'Brave 1.70', '$regex$Brave/1\.70(\.|$)', '1.70', '1.71', 2024, 2025, 'pause', (SELECT id FROM type_browser WHERE name = 'Brave' LIMIT 1)),
  ('Brave 1.80', '1.80', 'Brave 1.80', 'Brave 1.80', '$regex$Brave/1\.80(\.|$)', '1.80', '1.81', 2025, 2026, 'active', (SELECT id FROM type_browser WHERE name = 'Brave' LIMIT 1)),
  ('Brave 1.90', '1.90', 'Brave 1.90', 'Brave 1.90', '$regex$Brave/1\.90(\.|$)', '1.90', '1.91', 2026, 2026, 'active', (SELECT id FROM type_browser WHERE name = 'Brave' LIMIT 1)),
  ('Brave 1.97', '1.97', 'Brave 1.97', 'Brave 1.97', '$regex$Brave/1\.97(\.|$)', '1.97', '1.98', 2026, 0, 'active', (SELECT id FROM type_browser WHERE name = 'Brave' LIMIT 1))
ON CONFLICT (name) DO UPDATE SET
    version = EXCLUDED.version,
    description = EXCLUDED.description,
    match_name_exp = EXCLUDED.match_name_exp,
    match_ua_exp = EXCLUDED.match_ua_exp,
    match_ver_min_exp = EXCLUDED.match_ver_min_exp,
    match_ver_max_exp = EXCLUDED.match_ver_max_exp,
    year_release = EXCLUDED.year_release,
    year_end_support = EXCLUDED.year_end_support,
    active = EXCLUDED.active,
    parent_id = EXCLUDED.parent_id,
    updated_at = NOW();

-- Versions of UC Browser
INSERT INTO type_browser (name, version, description, match_name_exp, match_ua_exp, match_ver_min_exp, match_ver_max_exp, year_release, year_end_support, active, parent_id)
VALUES
  ('UC Browser 7', '7.0', 'UC Browser 7', 'UC Browser 7', '$regex$UCBrowser/7(\.|$)', '7.0', '8.0', 2010, 2012, 'pause', (SELECT id FROM type_browser WHERE name = 'UC Browser' LIMIT 1)),
  ('UC Browser 8', '8.0', 'UC Browser 8', 'UC Browser 8', '$regex$UCBrowser/8(\.|$)', '8.0', '9.0', 2011, 2014, 'pause', (SELECT id FROM type_browser WHERE name = 'UC Browser' LIMIT 1)),
  ('UC Browser 9', '9.0', 'UC Browser 9', 'UC Browser 9', '$regex$UCBrowser/9(\.|$)', '9.0', '10.0', 2013, 2015, 'pause', (SELECT id FROM type_browser WHERE name = 'UC Browser' LIMIT 1)),
  ('UC Browser 10', '10.0', 'UC Browser 10', 'UC Browser 10', '$regex$UCBrowser/10(\.|$)', '10.0', '11.0', 2014, 2017, 'pause', (SELECT id FROM type_browser WHERE name = 'UC Browser' LIMIT 1)),
  ('UC Browser 11', '11.0', 'UC Browser 11', 'UC Browser 11', '$regex$UCBrowser/11(\.|$)', '11.0', '12.0', 2016, 2019, 'pause', (SELECT id FROM type_browser WHERE name = 'UC Browser' LIMIT 1)),
  ('UC Browser 12', '12.0', 'UC Browser 12', 'UC Browser 12', '$regex$UCBrowser/12(\.|$)', '12.0', '13.0', 2017, 2021, 'pause', (SELECT id FROM type_browser WHERE name = 'UC Browser' LIMIT 1)),
  ('UC Browser 13', '13.0', 'UC Browser 13', 'UC Browser 13', '$regex$UCBrowser/13(\.|$)', '13.0', '14.0', 2019, 2025, 'active', (SELECT id FROM type_browser WHERE name = 'UC Browser' LIMIT 1)),
  ('UC Browser 14', '14.0', 'UC Browser 14', 'UC Browser 14', '$regex$UCBrowser/14(\.|$)', '14.0', '15.0', 2021, 2025, 'active', (SELECT id FROM type_browser WHERE name = 'UC Browser' LIMIT 1)),
  ('UC Browser 15', '15.0', 'UC Browser 15', 'UC Browser 15', '$regex$UCBrowser/15(\.|$)', '15.0', '16.0', 2022, 2025, 'active', (SELECT id FROM type_browser WHERE name = 'UC Browser' LIMIT 1)),
  ('UC Browser 16', '16.0', 'UC Browser 16', 'UC Browser 16', '$regex$UCBrowser/16(\.|$)', '16.0', '17.0', 2023, 2025, 'active', (SELECT id FROM type_browser WHERE name = 'UC Browser' LIMIT 1)),
  ('UC Browser 17', '17.0', 'UC Browser 17', 'UC Browser 17', '$regex$UCBrowser/17(\.|$)', '17.0', '18.0', 2024, 0, 'active', (SELECT id FROM type_browser WHERE name = 'UC Browser' LIMIT 1))
ON CONFLICT (name) DO UPDATE SET
    version = EXCLUDED.version,
    description = EXCLUDED.description,
    match_name_exp = EXCLUDED.match_name_exp,
    match_ua_exp = EXCLUDED.match_ua_exp,
    match_ver_min_exp = EXCLUDED.match_ver_min_exp,
    match_ver_max_exp = EXCLUDED.match_ver_max_exp,
    year_release = EXCLUDED.year_release,
    year_end_support = EXCLUDED.year_end_support,
    active = EXCLUDED.active,
    parent_id = EXCLUDED.parent_id,
    updated_at = NOW();

-- Versions of Vivaldi
INSERT INTO type_browser (name, version, description, match_name_exp, match_ua_exp, match_ver_min_exp, match_ver_max_exp, year_release, year_end_support, active, parent_id)
VALUES
  ('Vivaldi 1', '1.0', 'Vivaldi 1', 'Vivaldi 1', '$regex$Vivaldi/1(\.|$)', '1.0', '2.0', 2016, 2019, 'pause', (SELECT id FROM type_browser WHERE name = 'Vivaldi' LIMIT 1)),
  ('Vivaldi 2', '2.0', 'Vivaldi 2', 'Vivaldi 2', '$regex$Vivaldi/2(\.|$)', '2.0', '3.0', 2018, 2021, 'pause', (SELECT id FROM type_browser WHERE name = 'Vivaldi' LIMIT 1)),
  ('Vivaldi 3', '3.0', 'Vivaldi 3', 'Vivaldi 3', '$regex$Vivaldi/3(\.|$)', '3.0', '4.0', 2020, 2023, 'pause', (SELECT id FROM type_browser WHERE name = 'Vivaldi' LIMIT 1)),
  ('Vivaldi 4', '4.0', 'Vivaldi 4', 'Vivaldi 4', '$regex$Vivaldi/4(\.|$)', '4.0', '5.0', 2021, 2024, 'pause', (SELECT id FROM type_browser WHERE name = 'Vivaldi' LIMIT 1)),
  ('Vivaldi 5', '5.0', 'Vivaldi 5', 'Vivaldi 5', '$regex$Vivaldi/5(\.|$)', '5.0', '6.0', 2021, 2024, 'pause', (SELECT id FROM type_browser WHERE name = 'Vivaldi' LIMIT 1)),
  ('Vivaldi 6', '6.0', 'Vivaldi 6', 'Vivaldi 6', '$regex$Vivaldi/6(\.|$)', '6.0', '7.0', 2023, 2024, 'pause', (SELECT id FROM type_browser WHERE name = 'Vivaldi' LIMIT 1)),
  ('Vivaldi 7', '7.0', 'Vivaldi 7', 'Vivaldi 7', '$regex$Vivaldi/7(\.|$)', '7.0', '8.0', 2024, 2026, 'active', (SELECT id FROM type_browser WHERE name = 'Vivaldi' LIMIT 1)),
  ('Vivaldi 8', '8.0', 'Vivaldi 8.0', 'Vivaldi 8', '$regex$Vivaldi/8(\.|$)', '8.0', '9.0', 2026, 0, 'active', (SELECT id FROM type_browser WHERE name = 'Vivaldi' LIMIT 1))
ON CONFLICT (name) DO UPDATE SET
    version = EXCLUDED.version,
    description = EXCLUDED.description,
    match_name_exp = EXCLUDED.match_name_exp,
    match_ua_exp = EXCLUDED.match_ua_exp,
    match_ver_min_exp = EXCLUDED.match_ver_min_exp,
    match_ver_max_exp = EXCLUDED.match_ver_max_exp,
    year_release = EXCLUDED.year_release,
    year_end_support = EXCLUDED.year_end_support,
    active = EXCLUDED.active,
    parent_id = EXCLUDED.parent_id,
    updated_at = NOW();

-- Versions of Opera
INSERT INTO type_browser (name, version, description, match_name_exp, match_ua_exp, match_ver_min_exp, match_ver_max_exp, year_release, year_end_support, active, parent_id)
VALUES
  ('Opera 2', '2.0', 'Opera: versions 2–9; range [2.0, 10.0)', 'Opera 2', '$regex$(?:Version|Opera)/[2-9](\.|$)', '2.0', '10.0', 1996, 2009, 'pause', (SELECT id FROM type_browser WHERE name = 'Opera' LIMIT 1)),
  ('Opera 10', '10.0', 'Opera: versions 10–19; range [10.0, 20.0)', 'Opera 10', '$regex$(?:(?:Version|Opera)/1[0-9](\.|$)|OPR/1[0-9](\.|$))', '10.0', '20.0', 2009, 2017, 'pause', (SELECT id FROM type_browser WHERE name = 'Opera' LIMIT 1)),
  ('Opera 20', '20.0', 'Opera: versions 20–29; range [20.0, 30.0)', 'Opera 20', '$regex$OPR/2[0-9](\.|$)', '20.0', '30.0', 2014, 2018, 'pause', (SELECT id FROM type_browser WHERE name = 'Opera' LIMIT 1)),
  ('Opera 30', '30.0', 'Opera: versions 30–39; range [30.0, 40.0)', 'Opera 30', '$regex$OPR/3[0-9](\.|$)', '30.0', '40.0', 2015, 2019, 'pause', (SELECT id FROM type_browser WHERE name = 'Opera' LIMIT 1)),
  ('Opera 40', '40.0', 'Opera: versions 40–49; range [40.0, 50.0)', 'Opera 40', '$regex$OPR/4[0-9](\.|$)', '40.0', '50.0', 2016, 2020, 'pause', (SELECT id FROM type_browser WHERE name = 'Opera' LIMIT 1)),
  ('Opera 50', '50.0', 'Opera: versions 50–59; range [50.0, 60.0)', 'Opera 50', '$regex$OPR/5[0-9](\.|$)', '50.0', '60.0', 2018, 2022, 'pause', (SELECT id FROM type_browser WHERE name = 'Opera' LIMIT 1)),
  ('Opera 60', '60.0', 'Opera: versions 60–69; range [60.0, 70.0)', 'Opera 60', '$regex$OPR/6[0-9](\.|$)', '60.0', '70.0', 2019, 2023, 'pause', (SELECT id FROM type_browser WHERE name = 'Opera' LIMIT 1)),
  ('Opera 70', '70.0', 'Opera: versions 70–79; range [70.0, 80.0)', 'Opera 70', '$regex$OPR/7[0-9](\.|$)', '70.0', '80.0', 2020, 2024, 'pause', (SELECT id FROM type_browser WHERE name = 'Opera' LIMIT 1)),
  ('Opera 80', '80.0', 'Opera: versions 80–89; range [80.0, 90.0)', 'Opera 80', '$regex$OPR/8[0-9](\.|$)', '80.0', '90.0', 2021, 2025, 'pause', (SELECT id FROM type_browser WHERE name = 'Opera' LIMIT 1)),
  ('Opera 90', '90.0', 'Opera: versions 90–99; range [90.0, 100.0)', 'Opera 90', '$regex$OPR/9[0-9](\.|$)', '90.0', '100.0', 2022, 2025, 'pause', (SELECT id FROM type_browser WHERE name = 'Opera' LIMIT 1)),
  ('Opera 100', '100.0', 'Opera: versions 100–109; range [100.0, 110.0)', 'Opera 100', '$regex$OPR/10[0-9](\.|$)', '100.0', '110.0', 2023, 2024, 'pause', (SELECT id FROM type_browser WHERE name = 'Opera' LIMIT 1)),
  ('Opera 110', '110.0', 'Opera: versions 110–119; range [110.0, 120.0)', 'Opera 110', '$regex$OPR/11[0-9](\.|$)', '110.0', '120.0', 2024, 2025, 'active', (SELECT id FROM type_browser WHERE name = 'Opera' LIMIT 1)),
  ('Opera 120', '120.0', 'Opera: versions 120–129; range [120.0, 130.0)', 'Opera 120', '$regex$OPR/12[0-9](\.|$)', '120.0', '130.0', 2025, 2026, 'active', (SELECT id FROM type_browser WHERE name = 'Opera' LIMIT 1)),
  ('Opera 130', '130.0', 'Opera: versions 130–139; range [130.0, 140.0)', 'Opera 130', '$regex$OPR/13[0-9](\.|$)', '130.0', '140.0', 2026, 0, 'active', (SELECT id FROM type_browser WHERE name = 'Opera' LIMIT 1))
ON CONFLICT (name) DO UPDATE SET
    version = EXCLUDED.version,
    description = EXCLUDED.description,
    match_name_exp = EXCLUDED.match_name_exp,
    match_ua_exp = EXCLUDED.match_ua_exp,
    match_ver_min_exp = EXCLUDED.match_ver_min_exp,
    match_ver_max_exp = EXCLUDED.match_ver_max_exp,
    year_release = EXCLUDED.year_release,
    year_end_support = EXCLUDED.year_end_support,
    active = EXCLUDED.active,
    parent_id = EXCLUDED.parent_id,
    updated_at = NOW();

-- Versions of Opera Mini
INSERT INTO type_browser (name, version, description, match_name_exp, match_ua_exp, match_ver_min_exp, match_ver_max_exp, year_release, year_end_support, active, parent_id)
VALUES
  ('Opera Mini 7', '7.0', 'Opera Mini 7', 'Opera Mini 7', '$regex$Opera Mini/7(\.|$)', '7.0', '8.0', 2012, 2015, 'pause', (SELECT id FROM type_browser WHERE name = 'Opera Mini' LIMIT 1)),
  ('Opera Mini 8', '8.0', 'Opera Mini 8', 'Opera Mini 8', '$regex$Opera Mini/8(\.|$)', '8.0', '9.0', 2012, 2015, 'pause', (SELECT id FROM type_browser WHERE name = 'Opera Mini' LIMIT 1)),
  ('Opera Mini 9', '9.0', 'Opera Mini 9', 'Opera Mini 9', '$regex$Opera Mini/9(\.|$)', '9.0', '10.0', 2012, 2015, 'pause', (SELECT id FROM type_browser WHERE name = 'Opera Mini' LIMIT 1)),
  ('Opera Mini 10', '10.0', 'Opera Mini 10', 'Opera Mini 10', '$regex$Opera Mini/10(\.|$)', '10.0', '11.0', 2012, 2015, 'pause', (SELECT id FROM type_browser WHERE name = 'Opera Mini' LIMIT 1)),
  ('Opera Mini 20', '20.0', 'Opera Mini 20', 'Opera Mini 20', '$regex$Opera Mini/20(\.|$)', '20.0', '21.0', 2014, 2017, 'pause', (SELECT id FROM type_browser WHERE name = 'Opera Mini' LIMIT 1)),
  ('Opera Mini 30', '30.0', 'Opera Mini 30', 'Opera Mini 30', '$regex$Opera Mini/30(\.|$)', '30.0', '31.0', 2016, 2019, 'pause', (SELECT id FROM type_browser WHERE name = 'Opera Mini' LIMIT 1)),
  ('Opera Mini 40', '40.0', 'Opera Mini 40', 'Opera Mini 40', '$regex$Opera Mini/40(\.|$)', '40.0', '41.0', 2018, 2021, 'pause', (SELECT id FROM type_browser WHERE name = 'Opera Mini' LIMIT 1)),
  ('Opera Mini 50', '50.0', 'Opera Mini 50', 'Opera Mini 50', '$regex$Opera Mini/50(\.|$)', '50.0', '51.0', 2020, 2023, 'active', (SELECT id FROM type_browser WHERE name = 'Opera Mini' LIMIT 1)),
  ('Opera Mini 60', '60.0', 'Opera Mini 60', 'Opera Mini 60', '$regex$Opera Mini/60(\.|$)', '60.0', '61.0', 2022, 2025, 'active', (SELECT id FROM type_browser WHERE name = 'Opera Mini' LIMIT 1)),
  ('Opera Mini 70', '70.0', 'Opera Mini 70', 'Opera Mini 70', '$regex$Opera Mini/70(\.|$)', '70.0', '71.0', 2024, 2026, 'active', (SELECT id FROM type_browser WHERE name = 'Opera Mini' LIMIT 1)),
  ('Opera Mini 80', '80.0', 'Opera Mini 80', 'Opera Mini 80', '$regex$Opera Mini/80(\.|$)', '80.0', '81.0', 2026, 0, 'active', (SELECT id FROM type_browser WHERE name = 'Opera Mini' LIMIT 1))
ON CONFLICT (name) DO UPDATE SET
    version = EXCLUDED.version,
    description = EXCLUDED.description,
    match_name_exp = EXCLUDED.match_name_exp,
    match_ua_exp = EXCLUDED.match_ua_exp,
    match_ver_min_exp = EXCLUDED.match_ver_min_exp,
    match_ver_max_exp = EXCLUDED.match_ver_max_exp,
    year_release = EXCLUDED.year_release,
    year_end_support = EXCLUDED.year_end_support,
    active = EXCLUDED.active,
    parent_id = EXCLUDED.parent_id,
    updated_at = NOW();

-- Versions of Samsung Internet
INSERT INTO type_browser (name, version, description, match_name_exp, match_ua_exp, match_ver_min_exp, match_ver_max_exp, year_release, year_end_support, active, parent_id)
VALUES
  ('Samsung Internet 1', '1.0', 'Samsung Internet: all 1.x versions; range [1.0, 2.0)', 'Samsung Internet 1', '$regex$SamsungBrowser/1(\.|$)', '1.0', '2.0', 2013, 2017, 'pause', (SELECT id FROM type_browser WHERE name = 'Samsung Internet' LIMIT 1)),
  ('Samsung Internet 2', '2.0', 'Samsung Internet: all 2.x versions; range [2.0, 3.0)', 'Samsung Internet 2', '$regex$SamsungBrowser/2(\.|$)', '2.0', '3.0', 2014, 2018, 'pause', (SELECT id FROM type_browser WHERE name = 'Samsung Internet' LIMIT 1)),
  ('Samsung Internet 3', '3.0', 'Samsung Internet: all 3.x versions; range [3.0, 4.0)', 'Samsung Internet 3', '$regex$SamsungBrowser/3(\.|$)', '3.0', '4.0', 2015, 2018, 'pause', (SELECT id FROM type_browser WHERE name = 'Samsung Internet' LIMIT 1)),
  ('Samsung Internet 4', '4.0', 'Samsung Internet: all 4.x versions; range [4.0, 5.0)', 'Samsung Internet 4', '$regex$SamsungBrowser/4(\.|$)', '4.0', '5.0', 2016, 2019, 'pause', (SELECT id FROM type_browser WHERE name = 'Samsung Internet' LIMIT 1)),
  ('Samsung Internet 5', '5.0', 'Samsung Internet: all 5.x versions; range [5.0, 6.0)', 'Samsung Internet 5', '$regex$SamsungBrowser/5(\.|$)', '5.0', '6.0', 2016, 2020, 'pause', (SELECT id FROM type_browser WHERE name = 'Samsung Internet' LIMIT 1)),
  ('Samsung Internet 6', '6.0', 'Samsung Internet: all 6.x versions; range [6.0, 7.0)', 'Samsung Internet 6', '$regex$SamsungBrowser/6(\.|$)', '6.0', '7.0', 2017, 2021, 'pause', (SELECT id FROM type_browser WHERE name = 'Samsung Internet' LIMIT 1)),
  ('Samsung Internet 7', '7.0', 'Samsung Internet: all 7.x versions; range [7.0, 8.0)', 'Samsung Internet 7', '$regex$SamsungBrowser/7(\.|$)', '7.0', '8.0', 2018, 2021, 'pause', (SELECT id FROM type_browser WHERE name = 'Samsung Internet' LIMIT 1)),
  ('Samsung Internet 8', '8.0', 'Samsung Internet: all 8.x versions; range [8.0, 9.0)', 'Samsung Internet 8', '$regex$SamsungBrowser/8(\.|$)', '8.0', '9.0', 2018, 2021, 'pause', (SELECT id FROM type_browser WHERE name = 'Samsung Internet' LIMIT 1)),
  ('Samsung Internet 9', '9.0', 'Samsung Internet: all 9.x versions; range [9.0, 10.0)', 'Samsung Internet 9', '$regex$SamsungBrowser/9(\.|$)', '9.0', '10.0', 2018, 2022, 'pause', (SELECT id FROM type_browser WHERE name = 'Samsung Internet' LIMIT 1)),
  ('Samsung Internet 10', '10.0', 'Samsung Internet: all 10.x versions; range [10.0, 11.0)', 'Samsung Internet 10', '$regex$SamsungBrowser/10(\.|$)', '10.0', '11.0', 2019, 2022, 'pause', (SELECT id FROM type_browser WHERE name = 'Samsung Internet' LIMIT 1)),
  ('Samsung Internet 11', '11.0', 'Samsung Internet: all 11.x versions; range [11.0, 12.0)', 'Samsung Internet 11', '$regex$SamsungBrowser/11(\.|$)', '11.0', '12.0', 2019, 2023, 'pause', (SELECT id FROM type_browser WHERE name = 'Samsung Internet' LIMIT 1)),
  ('Samsung Internet 12', '12.0', 'Samsung Internet: all 12.x versions; range [12.0, 13.0)', 'Samsung Internet 12', '$regex$SamsungBrowser/12(\.|$)', '12.0', '13.0', 2020, 2023, 'pause', (SELECT id FROM type_browser WHERE name = 'Samsung Internet' LIMIT 1)),
  ('Samsung Internet 13', '13.0', 'Samsung Internet: all 13.x versions; range [13.0, 14.0)', 'Samsung Internet 13', '$regex$SamsungBrowser/13(\.|$)', '13.0', '14.0', 2020, 2024, 'pause', (SELECT id FROM type_browser WHERE name = 'Samsung Internet' LIMIT 1)),
  ('Samsung Internet 14', '14.0', 'Samsung Internet: all 14.x versions; range [14.0, 15.0)', 'Samsung Internet 14', '$regex$SamsungBrowser/14(\.|$)', '14.0', '15.0', 2021, 2024, 'pause', (SELECT id FROM type_browser WHERE name = 'Samsung Internet' LIMIT 1)),
  ('Samsung Internet 15', '15.0', 'Samsung Internet 15.0', 'Samsung Internet 15', '$regex$SamsungBrowser/15(\.|$)', '15.0', '16.0', 2021, 2024, 'pause', (SELECT id FROM type_browser WHERE name = 'Samsung Internet' LIMIT 1)),
  ('Samsung Internet 16', '16.0', 'Samsung Internet: all 16.x versions; range [16.0, 17.0)', 'Samsung Internet 16', '$regex$SamsungBrowser/16(\.|$)', '16.0', '17.0', 2021, 2025, 'pause', (SELECT id FROM type_browser WHERE name = 'Samsung Internet' LIMIT 1)),
  ('Samsung Internet 17', '17.0', 'Samsung Internet 17.0', 'Samsung Internet 17', '$regex$SamsungBrowser/17(\.|$)', '17.0', '18.0', 2022, 2025, 'pause', (SELECT id FROM type_browser WHERE name = 'Samsung Internet' LIMIT 1)),
  ('Samsung Internet 18', '18.0', 'Samsung Internet: all 18.x versions; range [18.0, 19.0)', 'Samsung Internet 18', '$regex$SamsungBrowser/18(\.|$)', '18.0', '19.0', 2022, 2025, 'pause', (SELECT id FROM type_browser WHERE name = 'Samsung Internet' LIMIT 1)),
  ('Samsung Internet 19', '19.0', 'Samsung Internet: all 19.x versions; range [19.0, 20.0)', 'Samsung Internet 19', '$regex$SamsungBrowser/19(\.|$)', '19.0', '20.0', 2022, 2025, 'pause', (SELECT id FROM type_browser WHERE name = 'Samsung Internet' LIMIT 1)),
  ('Samsung Internet 20', '20.0', 'Samsung Internet 20.0', 'Samsung Internet 20', '$regex$SamsungBrowser/20(\.|$)', '20.0', '21.0', 2023, 2023, 'pause', (SELECT id FROM type_browser WHERE name = 'Samsung Internet' LIMIT 1)),
  ('Samsung Internet 21', '21.0', 'Samsung Internet 21.0', 'Samsung Internet 21', '$regex$SamsungBrowser/21(\.|$)', '21.0', '22.0', 2023, 2023, 'pause', (SELECT id FROM type_browser WHERE name = 'Samsung Internet' LIMIT 1)),
  ('Samsung Internet 22', '22.0', 'Samsung Internet 22.0', 'Samsung Internet 22', '$regex$SamsungBrowser/22(\.|$)', '22.0', '23.0', 2023, 2023, 'pause', (SELECT id FROM type_browser WHERE name = 'Samsung Internet' LIMIT 1)),
  ('Samsung Internet 23', '23.0', 'Samsung Internet 23.0', 'Samsung Internet 23', '$regex$SamsungBrowser/23(\.|$)', '23.0', '24.0', 2023, 2024, 'pause', (SELECT id FROM type_browser WHERE name = 'Samsung Internet' LIMIT 1)),
  ('Samsung Internet 24', '24.0', 'Samsung Internet 24.0', 'Samsung Internet 24', '$regex$SamsungBrowser/24(\.|$)', '24.0', '25.0', 2024, 2024, 'pause', (SELECT id FROM type_browser WHERE name = 'Samsung Internet' LIMIT 1)),
  ('Samsung Internet 25', '25.0', 'Samsung Internet 25.0', 'Samsung Internet 25', '$regex$SamsungBrowser/25(\.|$)', '25.0', '26.0', 2024, 2024, 'pause', (SELECT id FROM type_browser WHERE name = 'Samsung Internet' LIMIT 1)),
  ('Samsung Internet 26', '26.0', 'Samsung Internet 26.0', 'Samsung Internet 26', '$regex$SamsungBrowser/26(\.|$)', '26.0', '27.0', 2024, 2024, 'pause', (SELECT id FROM type_browser WHERE name = 'Samsung Internet' LIMIT 1)),
  ('Samsung Internet 27', '27.0', 'Samsung Internet 27.0', 'Samsung Internet 27', '$regex$SamsungBrowser/27(\.|$)', '27.0', '28.0', 2024, 2025, 'active', (SELECT id FROM type_browser WHERE name = 'Samsung Internet' LIMIT 1)),
  ('Samsung Internet 28', '28.0', 'Samsung Internet 28.0', 'Samsung Internet 28', '$regex$SamsungBrowser/28(\.|$)', '28.0', '29.0', 2025, 2025, 'active', (SELECT id FROM type_browser WHERE name = 'Samsung Internet' LIMIT 1)),
  ('Samsung Internet 29', '29.0', 'Samsung Internet 29.0', 'Samsung Internet 29', '$regex$SamsungBrowser/29(\.|$)', '29.0', '30.0', 2025, 2026, 'active', (SELECT id FROM type_browser WHERE name = 'Samsung Internet' LIMIT 1)),
  ('Samsung Internet 30', '30.0', 'Samsung Internet 30.0', 'Samsung Internet 30', '$regex$SamsungBrowser/30(\.|$)', '30.0', '31.0', 2026, 0, 'active', (SELECT id FROM type_browser WHERE name = 'Samsung Internet' LIMIT 1))
ON CONFLICT (name) DO UPDATE SET
    version = EXCLUDED.version,
    description = EXCLUDED.description,
    match_name_exp = EXCLUDED.match_name_exp,
    match_ua_exp = EXCLUDED.match_ua_exp,
    match_ver_min_exp = EXCLUDED.match_ver_min_exp,
    match_ver_max_exp = EXCLUDED.match_ver_max_exp,
    year_release = EXCLUDED.year_release,
    year_end_support = EXCLUDED.year_end_support,
    active = EXCLUDED.active,
    parent_id = EXCLUDED.parent_id,
    updated_at = NOW();

-- Versions of Android WebView
INSERT INTO type_browser (name, version, description, match_name_exp, match_ua_exp, match_ver_min_exp, match_ver_max_exp, year_release, year_end_support, active, parent_id)
VALUES
  ('Android WebView 30', '30.0', 'Android WebView: versions 30–39; range [30.0, 40.0)', 'Android WebView 30', '$regex$(?=.*; wv\))(?=.*Chrome/3[0-9](\.|$))', '30.0', '40.0', 2014, 2017, 'pause', (SELECT id FROM type_browser WHERE name = 'Android WebView' LIMIT 1)),
  ('Android WebView 40', '40.0', 'Android WebView: versions 40–49; range [40.0, 50.0)', 'Android WebView 40', '$regex$(?=.*; wv\))(?=.*Chrome/4[0-9](\.|$))', '40.0', '50.0', 2015, 2019, 'pause', (SELECT id FROM type_browser WHERE name = 'Android WebView' LIMIT 1)),
  ('Android WebView 50', '50.0', 'Android WebView: versions 50–59; range [50.0, 60.0)', 'Android WebView 50', '$regex$(?=.*; wv\))(?=.*Chrome/5[0-9](\.|$))', '50.0', '60.0', 2016, 2020, 'pause', (SELECT id FROM type_browser WHERE name = 'Android WebView' LIMIT 1)),
  ('Android WebView 60', '60.0', 'Android WebView: versions 60–69; range [60.0, 70.0)', 'Android WebView 60', '$regex$(?=.*; wv\))(?=.*Chrome/6[0-9](\.|$))', '60.0', '70.0', 2017, 2021, 'pause', (SELECT id FROM type_browser WHERE name = 'Android WebView' LIMIT 1)),
  ('Android WebView 70', '70.0', 'Android WebView: versions 70–79; range [70.0, 80.0)', 'Android WebView 70', '$regex$(?=.*; wv\))(?=.*Chrome/7[0-9](\.|$))', '70.0', '80.0', 2018, 2022, 'pause', (SELECT id FROM type_browser WHERE name = 'Android WebView' LIMIT 1)),
  ('Android WebView 80', '80.0', 'Android WebView: versions 80–89; range [80.0, 90.0)', 'Android WebView 80', '$regex$(?=.*; wv\))(?=.*Chrome/8[0-9](\.|$))', '80.0', '90.0', 2020, 2024, 'pause', (SELECT id FROM type_browser WHERE name = 'Android WebView' LIMIT 1)),
  ('Android WebView 90', '90.0', 'Android WebView: versions 90–99; range [90.0, 100.0)', 'Android WebView 90', '$regex$(?=.*; wv\))(?=.*Chrome/9[0-9](\.|$))', '90.0', '100.0', 2021, 2025, 'pause', (SELECT id FROM type_browser WHERE name = 'Android WebView' LIMIT 1)),
  ('Android WebView 100', '100.0', 'Android WebView: versions 100–109; range [100.0, 110.0)', 'Android WebView 100', '$regex$(?=.*; wv\))(?=.*Chrome/10[0-9](\.|$))', '100.0', '110.0', 2022, 2025, 'pause', (SELECT id FROM type_browser WHERE name = 'Android WebView' LIMIT 1)),
  ('Android WebView 110', '110.0', 'Android WebView: versions 110–119; range [110.0, 120.0)', 'Android WebView 110', '$regex$(?=.*; wv\))(?=.*Chrome/11[0-9](\.|$))', '110.0', '120.0', 2023, 2023, 'pause', (SELECT id FROM type_browser WHERE name = 'Android WebView' LIMIT 1)),
  ('Android WebView 120', '120.0', 'Android WebView: versions 120–129; range [120.0, 130.0)', 'Android WebView 120', '$regex$(?=.*; wv\))(?=.*Chrome/12[0-9](\.|$))', '120.0', '130.0', 2023, 2024, 'pause', (SELECT id FROM type_browser WHERE name = 'Android WebView' LIMIT 1)),
  ('Android WebView 130', '130.0', 'Android WebView: versions 130–139; range [130.0, 140.0)', 'Android WebView 130', '$regex$(?=.*; wv\))(?=.*Chrome/13[0-9](\.|$))', '130.0', '140.0', 2024, 2025, 'active', (SELECT id FROM type_browser WHERE name = 'Android WebView' LIMIT 1)),
  ('Android WebView 140', '140.0', 'Android WebView: versions 140–149; range [140.0, 150.0)', 'Android WebView 140', '$regex$(?=.*; wv\))(?=.*Chrome/14[0-9](\.|$))', '140.0', '150.0', 2025, 2026, 'active', (SELECT id FROM type_browser WHERE name = 'Android WebView' LIMIT 1)),
  ('Android WebView 150', '150.0', 'Android WebView: versions 150–159; range [150.0, 160.0)', 'Android WebView 150', '$regex$(?=.*; wv\))(?=.*Chrome/15[0-9](\.|$))', '150.0', '160.0', 2026, 0, 'active', (SELECT id FROM type_browser WHERE name = 'Android WebView' LIMIT 1))
ON CONFLICT (name) DO UPDATE SET
    version = EXCLUDED.version,
    description = EXCLUDED.description,
    match_name_exp = EXCLUDED.match_name_exp,
    match_ua_exp = EXCLUDED.match_ua_exp,
    match_ver_min_exp = EXCLUDED.match_ver_min_exp,
    match_ver_max_exp = EXCLUDED.match_ver_max_exp,
    year_release = EXCLUDED.year_release,
    year_end_support = EXCLUDED.year_end_support,
    active = EXCLUDED.active,
    parent_id = EXCLUDED.parent_id,
    updated_at = NOW();

-- Versions of Amazon Silk
INSERT INTO type_browser (name, version, description, match_name_exp, match_ua_exp, match_ver_min_exp, match_ver_max_exp, year_release, year_end_support, active, parent_id)
VALUES
  ('Silk 50', '50.0', 'Amazon Silk: versions 50–59; range [50.0, 60.0)', 'Silk 50', '$regex$Silk/5[0-9](\.|$)', '50.0', '60.0', 2016, 2019, 'pause', (SELECT id FROM type_browser WHERE name = 'Amazon Silk' LIMIT 1)),
  ('Silk 60', '60.0', 'Amazon Silk: versions 60–69; range [60.0, 70.0)', 'Silk 60', '$regex$Silk/6[0-9](\.|$)', '60.0', '70.0', 2017, 2020, 'pause', (SELECT id FROM type_browser WHERE name = 'Amazon Silk' LIMIT 1)),
  ('Silk 70', '70.0', 'Amazon Silk: versions 70–79; range [70.0, 80.0)', 'Silk 70', '$regex$Silk/7[0-9](\.|$)', '70.0', '80.0', 2018, 2021, 'pause', (SELECT id FROM type_browser WHERE name = 'Amazon Silk' LIMIT 1)),
  ('Silk 80', '80.0', 'Amazon Silk: versions 80–89; range [80.0, 90.0)', 'Silk 80', '$regex$Silk/8[0-9](\.|$)', '80.0', '90.0', 2020, 2023, 'pause', (SELECT id FROM type_browser WHERE name = 'Amazon Silk' LIMIT 1)),
  ('Silk 90', '90.0', 'Amazon Silk: versions 90–99; range [90.0, 100.0)', 'Silk 90', '$regex$Silk/9[0-9](\.|$)', '90.0', '100.0', 2021, 2024, 'active', (SELECT id FROM type_browser WHERE name = 'Amazon Silk' LIMIT 1)),
  ('Silk 100', '100.0', 'Amazon Silk: versions 100–109; range [100.0, 110.0)', 'Silk 100', '$regex$Silk/10[0-9](\.|$)', '100.0', '110.0', 2022, 2025, 'active', (SELECT id FROM type_browser WHERE name = 'Amazon Silk' LIMIT 1)),
  ('Silk 110', '110.0', 'Amazon Silk: versions 110–119; range [110.0, 120.0)', 'Silk 110', '$regex$Silk/11[0-9](\.|$)', '110.0', '120.0', 2023, 2023, 'active', (SELECT id FROM type_browser WHERE name = 'Amazon Silk' LIMIT 1)),
  ('Silk 120', '120.0', 'Amazon Silk: versions 120–129; range [120.0, 130.0)', 'Silk 120', '$regex$Silk/12[0-9](\.|$)', '120.0', '130.0', 2023, 2024, 'active', (SELECT id FROM type_browser WHERE name = 'Amazon Silk' LIMIT 1)),
  ('Silk 130', '130.0', 'Amazon Silk: versions 130–139; range [130.0, 140.0)', 'Silk 130', '$regex$Silk/13[0-9](\.|$)', '130.0', '140.0', 2024, 2025, 'active', (SELECT id FROM type_browser WHERE name = 'Amazon Silk' LIMIT 1)),
  ('Silk 140', '140.0', 'Amazon Silk: versions 140–149; range [140.0, 150.0)', 'Silk 140', '$regex$Silk/14[0-9](\.|$)', '140.0', '150.0', 2025, 0, 'active', (SELECT id FROM type_browser WHERE name = 'Amazon Silk' LIMIT 1))
ON CONFLICT (name) DO UPDATE SET
    version = EXCLUDED.version,
    description = EXCLUDED.description,
    match_name_exp = EXCLUDED.match_name_exp,
    match_ua_exp = EXCLUDED.match_ua_exp,
    match_ver_min_exp = EXCLUDED.match_ver_min_exp,
    match_ver_max_exp = EXCLUDED.match_ver_max_exp,
    year_release = EXCLUDED.year_release,
    year_end_support = EXCLUDED.year_end_support,
    active = EXCLUDED.active,
    parent_id = EXCLUDED.parent_id,
    updated_at = NOW();

-- Versions of Huawei Browser
INSERT INTO type_browser (name, version, description, match_name_exp, match_ua_exp, match_ver_min_exp, match_ver_max_exp, year_release, year_end_support, active, parent_id)
VALUES
  ('Huawei Browser 10', '10.0', 'Huawei Browser 10', 'Huawei Browser 10', '$regex$HuaweiBrowser/10(\.|$)', '10.0', '11.0', 2020, 2023, 'pause', (SELECT id FROM type_browser WHERE name = 'Huawei Browser' LIMIT 1)),
  ('Huawei Browser 11', '11.0', 'Huawei Browser 11', 'Huawei Browser 11', '$regex$HuaweiBrowser/11(\.|$)', '11.0', '12.0', 2021, 2024, 'active', (SELECT id FROM type_browser WHERE name = 'Huawei Browser' LIMIT 1)),
  ('Huawei Browser 12', '12.0', 'Huawei Browser 12', 'Huawei Browser 12', '$regex$HuaweiBrowser/12(\.|$)', '12.0', '13.0', 2022, 2025, 'active', (SELECT id FROM type_browser WHERE name = 'Huawei Browser' LIMIT 1)),
  ('Huawei Browser 13', '13.0', 'Huawei Browser 13', 'Huawei Browser 13', '$regex$HuaweiBrowser/13(\.|$)', '13.0', '14.0', 2023, 2024, 'active', (SELECT id FROM type_browser WHERE name = 'Huawei Browser' LIMIT 1)),
  ('Huawei Browser 14', '14.0', 'Huawei Browser 14', 'Huawei Browser 14', '$regex$HuaweiBrowser/14(\.|$)', '14.0', '15.0', 2024, 2025, 'active', (SELECT id FROM type_browser WHERE name = 'Huawei Browser' LIMIT 1)),
  ('Huawei Browser 15', '15.0', 'Huawei Browser 15', 'Huawei Browser 15', '$regex$HuaweiBrowser/15(\.|$)', '15.0', '16.0', 2025, 2026, 'active', (SELECT id FROM type_browser WHERE name = 'Huawei Browser' LIMIT 1)),
  ('Huawei Browser 16', '16.0', 'Huawei Browser 16', 'Huawei Browser 16', '$regex$HuaweiBrowser/16(\.|$)', '16.0', '17.0', 2026, 0, 'active', (SELECT id FROM type_browser WHERE name = 'Huawei Browser' LIMIT 1))
ON CONFLICT (name) DO UPDATE SET
    version = EXCLUDED.version,
    description = EXCLUDED.description,
    match_name_exp = EXCLUDED.match_name_exp,
    match_ua_exp = EXCLUDED.match_ua_exp,
    match_ver_min_exp = EXCLUDED.match_ver_min_exp,
    match_ver_max_exp = EXCLUDED.match_ver_max_exp,
    year_release = EXCLUDED.year_release,
    year_end_support = EXCLUDED.year_end_support,
    active = EXCLUDED.active,
    parent_id = EXCLUDED.parent_id,
    updated_at = NOW();

-- Versions of MIUI Browser
INSERT INTO type_browser (name, version, description, match_name_exp, match_ua_exp, match_ver_min_exp, match_ver_max_exp, year_release, year_end_support, active, parent_id)
VALUES
  ('MIUI Browser 10', '10.0', 'MIUI Browser 10', 'MIUI Browser 10', '$regex$MiuiBrowser/10(\.|$)', '10.0', '11.0', 2019, 2022, 'pause', (SELECT id FROM type_browser WHERE name = 'MIUI Browser' LIMIT 1)),
  ('MIUI Browser 11', '11.0', 'MIUI Browser 11', 'MIUI Browser 11', '$regex$MiuiBrowser/11(\.|$)', '11.0', '12.0', 2020, 2023, 'pause', (SELECT id FROM type_browser WHERE name = 'MIUI Browser' LIMIT 1)),
  ('MIUI Browser 12', '12.0', 'MIUI Browser 12', 'MIUI Browser 12', '$regex$MiuiBrowser/12(\.|$)', '12.0', '13.0', 2021, 2024, 'active', (SELECT id FROM type_browser WHERE name = 'MIUI Browser' LIMIT 1)),
  ('MIUI Browser 13', '13.0', 'MIUI Browser 13', 'MIUI Browser 13', '$regex$MiuiBrowser/13(\.|$)', '13.0', '14.0', 2022, 2025, 'active', (SELECT id FROM type_browser WHERE name = 'MIUI Browser' LIMIT 1)),
  ('MIUI Browser 14', '14.0', 'MIUI Browser 14', 'MIUI Browser 14', '$regex$MiuiBrowser/14(\.|$)', '14.0', '15.0', 2023, 2024, 'active', (SELECT id FROM type_browser WHERE name = 'MIUI Browser' LIMIT 1)),
  ('MIUI Browser 15', '15.0', 'MIUI Browser 15', 'MIUI Browser 15', '$regex$MiuiBrowser/15(\.|$)', '15.0', '16.0', 2024, 2025, 'active', (SELECT id FROM type_browser WHERE name = 'MIUI Browser' LIMIT 1)),
  ('MIUI Browser 16', '16.0', 'MIUI Browser 16', 'MIUI Browser 16', '$regex$MiuiBrowser/16(\.|$)', '16.0', '17.0', 2025, 2026, 'active', (SELECT id FROM type_browser WHERE name = 'MIUI Browser' LIMIT 1)),
  ('MIUI Browser 17', '17.0', 'MIUI Browser 17', 'MIUI Browser 17', '$regex$MiuiBrowser/17(\.|$)', '17.0', '18.0', 2026, 0, 'active', (SELECT id FROM type_browser WHERE name = 'MIUI Browser' LIMIT 1))
ON CONFLICT (name) DO UPDATE SET
    version = EXCLUDED.version,
    description = EXCLUDED.description,
    match_name_exp = EXCLUDED.match_name_exp,
    match_ua_exp = EXCLUDED.match_ua_exp,
    match_ver_min_exp = EXCLUDED.match_ver_min_exp,
    match_ver_max_exp = EXCLUDED.match_ver_max_exp,
    year_release = EXCLUDED.year_release,
    year_end_support = EXCLUDED.year_end_support,
    active = EXCLUDED.active,
    parent_id = EXCLUDED.parent_id,
    updated_at = NOW();

-- Versions of QQ Browser
INSERT INTO type_browser (name, version, description, match_name_exp, match_ua_exp, match_ver_min_exp, match_ver_max_exp, year_release, year_end_support, active, parent_id)
VALUES
  ('QQ Browser 10', '10.0', 'QQ Browser 10', 'QQ Browser 10', '$regex$MQQBrowser/10(\.|$)', '10.0', '11.0', 2018, 2021, 'pause', (SELECT id FROM type_browser WHERE name = 'QQ Browser' LIMIT 1)),
  ('QQ Browser 11', '11.0', 'QQ Browser 11', 'QQ Browser 11', '$regex$MQQBrowser/11(\.|$)', '11.0', '12.0', 2019, 2022, 'pause', (SELECT id FROM type_browser WHERE name = 'QQ Browser' LIMIT 1)),
  ('QQ Browser 12', '12.0', 'QQ Browser 12', 'QQ Browser 12', '$regex$MQQBrowser/12(\.|$)', '12.0', '13.0', 2020, 2023, 'pause', (SELECT id FROM type_browser WHERE name = 'QQ Browser' LIMIT 1)),
  ('QQ Browser 13', '13.0', 'QQ Browser 13', 'QQ Browser 13', '$regex$MQQBrowser/13(\.|$)', '13.0', '14.0', 2021, 2024, 'active', (SELECT id FROM type_browser WHERE name = 'QQ Browser' LIMIT 1)),
  ('QQ Browser 14', '14.0', 'QQ Browser 14', 'QQ Browser 14', '$regex$MQQBrowser/14(\.|$)', '14.0', '15.0', 2022, 2025, 'active', (SELECT id FROM type_browser WHERE name = 'QQ Browser' LIMIT 1)),
  ('QQ Browser 15', '15.0', 'QQ Browser 15', 'QQ Browser 15', '$regex$MQQBrowser/15(\.|$)', '15.0', '16.0', 2023, 2024, 'active', (SELECT id FROM type_browser WHERE name = 'QQ Browser' LIMIT 1)),
  ('QQ Browser 16', '16.0', 'QQ Browser 16', 'QQ Browser 16', '$regex$MQQBrowser/16(\.|$)', '16.0', '17.0', 2024, 0, 'active', (SELECT id FROM type_browser WHERE name = 'QQ Browser' LIMIT 1))
ON CONFLICT (name) DO UPDATE SET
    version = EXCLUDED.version,
    description = EXCLUDED.description,
    match_name_exp = EXCLUDED.match_name_exp,
    match_ua_exp = EXCLUDED.match_ua_exp,
    match_ver_min_exp = EXCLUDED.match_ver_min_exp,
    match_ver_max_exp = EXCLUDED.match_ver_max_exp,
    year_release = EXCLUDED.year_release,
    year_end_support = EXCLUDED.year_end_support,
    active = EXCLUDED.active,
    parent_id = EXCLUDED.parent_id,
    updated_at = NOW();

-- Versions of Naver Whale
INSERT INTO type_browser (name, version, description, match_name_exp, match_ua_exp, match_ver_min_exp, match_ver_max_exp, year_release, year_end_support, active, parent_id)
VALUES
  ('Whale 1', '1.0', 'Naver Whale 1', 'Whale 1', '$regex$Whale/1(\.|$)', '1.0', '2.0', 2017, 2020, 'pause', (SELECT id FROM type_browser WHERE name = 'Naver Whale' LIMIT 1)),
  ('Whale 2', '2.0', 'Naver Whale 2', 'Whale 2', '$regex$Whale/2(\.|$)', '2.0', '3.0', 2019, 2022, 'active', (SELECT id FROM type_browser WHERE name = 'Naver Whale' LIMIT 1)),
  ('Whale 3', '3.0', 'Naver Whale 3', 'Whale 3', '$regex$Whale/3(\.|$)', '3.0', '4.0', 2021, 2024, 'active', (SELECT id FROM type_browser WHERE name = 'Naver Whale' LIMIT 1)),
  ('Whale 4', '4.0', 'Naver Whale 4', 'Whale 4', '$regex$Whale/4(\.|$)', '4.0', '5.0', 2023, 2026, 'active', (SELECT id FROM type_browser WHERE name = 'Naver Whale' LIMIT 1))
ON CONFLICT (name) DO UPDATE SET
    version = EXCLUDED.version,
    description = EXCLUDED.description,
    match_name_exp = EXCLUDED.match_name_exp,
    match_ua_exp = EXCLUDED.match_ua_exp,
    match_ver_min_exp = EXCLUDED.match_ver_min_exp,
    match_ver_max_exp = EXCLUDED.match_ver_max_exp,
    year_release = EXCLUDED.year_release,
    year_end_support = EXCLUDED.year_end_support,
    active = EXCLUDED.active,
    parent_id = EXCLUDED.parent_id,
    updated_at = NOW();

-- Versions of DuckDuckGo
INSERT INTO type_browser (name, version, description, match_name_exp, match_ua_exp, match_ver_min_exp, match_ver_max_exp, year_release, year_end_support, active, parent_id)
VALUES
  ('DuckDuckGo 5', '5.0', 'DuckDuckGo 5', 'DuckDuckGo 5', '$regex$DuckDuckGo/5(\.|$)', '5.0', '6.0', 2021, 2024, 'active', (SELECT id FROM type_browser WHERE name = 'DuckDuckGo' LIMIT 1)),
  ('DuckDuckGo 6', '6.0', 'DuckDuckGo 6', 'DuckDuckGo 6', '$regex$DuckDuckGo/6(\.|$)', '6.0', '7.0', 2022, 2025, 'active', (SELECT id FROM type_browser WHERE name = 'DuckDuckGo' LIMIT 1)),
  ('DuckDuckGo 7', '7.0', 'DuckDuckGo 7', 'DuckDuckGo 7', '$regex$DuckDuckGo/7(\.|$)', '7.0', '8.0', 2023, 2024, 'active', (SELECT id FROM type_browser WHERE name = 'DuckDuckGo' LIMIT 1)),
  ('DuckDuckGo 8', '8.0', 'DuckDuckGo 8', 'DuckDuckGo 8', '$regex$DuckDuckGo/8(\.|$)', '8.0', '9.0', 2024, 0, 'active', (SELECT id FROM type_browser WHERE name = 'DuckDuckGo' LIMIT 1))
ON CONFLICT (name) DO UPDATE SET
    version = EXCLUDED.version,
    description = EXCLUDED.description,
    match_name_exp = EXCLUDED.match_name_exp,
    match_ua_exp = EXCLUDED.match_ua_exp,
    match_ver_min_exp = EXCLUDED.match_ver_min_exp,
    match_ver_max_exp = EXCLUDED.match_ver_max_exp,
    year_release = EXCLUDED.year_release,
    year_end_support = EXCLUDED.year_end_support,
    active = EXCLUDED.active,
    parent_id = EXCLUDED.parent_id,
    updated_at = NOW();

-- Versions of Facebook
INSERT INTO type_browser (name, version, description, match_name_exp, match_ua_exp, match_ver_min_exp, match_ver_max_exp, year_release, year_end_support, active, parent_id)
VALUES
  ('Facebook 200', '200.0', 'Facebook in-app 200', 'Facebook 200', '$regex$FBAV/200(\.|$)', '200.0', '201.0', 2020, 2023, 'pause', (SELECT id FROM type_browser WHERE name = 'Facebook' LIMIT 1)),
  ('Facebook 250', '250.0', 'Facebook in-app 250', 'Facebook 250', '$regex$FBAV/250(\.|$)', '250.0', '251.0', 2020, 2023, 'pause', (SELECT id FROM type_browser WHERE name = 'Facebook' LIMIT 1)),
  ('Facebook 300', '300.0', 'Facebook in-app 300', 'Facebook 300', '$regex$FBAV/300(\.|$)', '300.0', '301.0', 2021, 2024, 'active', (SELECT id FROM type_browser WHERE name = 'Facebook' LIMIT 1)),
  ('Facebook 350', '350.0', 'Facebook in-app 350', 'Facebook 350', '$regex$FBAV/350(\.|$)', '350.0', '351.0', 2021, 2024, 'active', (SELECT id FROM type_browser WHERE name = 'Facebook' LIMIT 1)),
  ('Facebook 400', '400.0', 'Facebook in-app 400', 'Facebook 400', '$regex$FBAV/400(\.|$)', '400.0', '401.0', 2022, 2025, 'active', (SELECT id FROM type_browser WHERE name = 'Facebook' LIMIT 1)),
  ('Facebook 450', '450.0', 'Facebook in-app 450', 'Facebook 450', '$regex$FBAV/450(\.|$)', '450.0', '451.0', 2023, 2023, 'active', (SELECT id FROM type_browser WHERE name = 'Facebook' LIMIT 1)),
  ('Facebook 500', '500.0', 'Facebook in-app 500', 'Facebook 500', '$regex$FBAV/500(\.|$)', '500.0', '501.0', 2023, 2026, 'active', (SELECT id FROM type_browser WHERE name = 'Facebook' LIMIT 1))
ON CONFLICT (name) DO UPDATE SET
    version = EXCLUDED.version,
    description = EXCLUDED.description,
    match_name_exp = EXCLUDED.match_name_exp,
    match_ua_exp = EXCLUDED.match_ua_exp,
    match_ver_min_exp = EXCLUDED.match_ver_min_exp,
    match_ver_max_exp = EXCLUDED.match_ver_max_exp,
    year_release = EXCLUDED.year_release,
    year_end_support = EXCLUDED.year_end_support,
    active = EXCLUDED.active,
    parent_id = EXCLUDED.parent_id,
    updated_at = NOW();

-- Versions of Instagram
INSERT INTO type_browser (name, version, description, match_name_exp, match_ua_exp, match_ver_min_exp, match_ver_max_exp, year_release, year_end_support, active, parent_id)
VALUES
  ('Instagram 200', '200.0', 'Instagram in-app 200', 'Instagram 200', '$regex$Instagram 200', '200.0', '201.0', 2021, 2024, 'active', (SELECT id FROM type_browser WHERE name = 'Instagram' LIMIT 1)),
  ('Instagram 220', '220.0', 'Instagram in-app 220', 'Instagram 220', '$regex$Instagram 220', '220.0', '221.0', 2021, 2024, 'active', (SELECT id FROM type_browser WHERE name = 'Instagram' LIMIT 1)),
  ('Instagram 240', '240.0', 'Instagram in-app 240', 'Instagram 240', '$regex$Instagram 240', '240.0', '241.0', 2021, 2024, 'active', (SELECT id FROM type_browser WHERE name = 'Instagram' LIMIT 1)),
  ('Instagram 260', '260.0', 'Instagram in-app 260', 'Instagram 260', '$regex$Instagram 260', '260.0', '261.0', 2022, 2025, 'active', (SELECT id FROM type_browser WHERE name = 'Instagram' LIMIT 1)),
  ('Instagram 280', '280.0', 'Instagram in-app 280', 'Instagram 280', '$regex$Instagram 280', '280.0', '281.0', 2022, 2025, 'active', (SELECT id FROM type_browser WHERE name = 'Instagram' LIMIT 1)),
  ('Instagram 300', '300.0', 'Instagram in-app 300', 'Instagram 300', '$regex$Instagram 300', '300.0', '301.0', 2023, 2023, 'active', (SELECT id FROM type_browser WHERE name = 'Instagram' LIMIT 1)),
  ('Instagram 320', '320.0', 'Instagram in-app 320', 'Instagram 320', '$regex$Instagram 320', '320.0', '321.0', 2023, 2023, 'active', (SELECT id FROM type_browser WHERE name = 'Instagram' LIMIT 1)),
  ('Instagram 340', '340.0', 'Instagram in-app 340', 'Instagram 340', '$regex$Instagram 340', '340.0', '341.0', 2023, 2024, 'active', (SELECT id FROM type_browser WHERE name = 'Instagram' LIMIT 1)),
  ('Instagram 360', '360.0', 'Instagram in-app 360', 'Instagram 360', '$regex$Instagram 360', '360.0', '361.0', 2024, 0, 'active', (SELECT id FROM type_browser WHERE name = 'Instagram' LIMIT 1))
ON CONFLICT (name) DO UPDATE SET
    version = EXCLUDED.version,
    description = EXCLUDED.description,
    match_name_exp = EXCLUDED.match_name_exp,
    match_ua_exp = EXCLUDED.match_ua_exp,
    match_ver_min_exp = EXCLUDED.match_ver_min_exp,
    match_ver_max_exp = EXCLUDED.match_ver_max_exp,
    year_release = EXCLUDED.year_release,
    year_end_support = EXCLUDED.year_end_support,
    active = EXCLUDED.active,
    parent_id = EXCLUDED.parent_id,
    updated_at = NOW();

-- Versions of Chrome iOS
INSERT INTO type_browser (name, version, description, match_name_exp, match_ua_exp, match_ver_min_exp, match_ver_max_exp, year_release, year_end_support, active, parent_id)
VALUES
  ('Chrome iOS 10', '10.0', 'Chrome iOS: versions 10–19; range [10.0, 20.0)', 'Chrome iOS 10', '$regex$CriOS/1[0-9](\.|$)', '10.0', '20.0', 2012, 2012, 'pause', (SELECT id FROM type_browser WHERE name = 'Chrome iOS' LIMIT 1)),
  ('Chrome iOS 20', '20.0', 'Chrome iOS: versions 20–29; range [20.0, 30.0)', 'Chrome iOS 20', '$regex$CriOS/2[0-9](\.|$)', '20.0', '30.0', 2012, 2013, 'pause', (SELECT id FROM type_browser WHERE name = 'Chrome iOS' LIMIT 1)),
  ('Chrome iOS 30', '30.0', 'Chrome iOS: versions 30–39; range [30.0, 40.0)', 'Chrome iOS 30', '$regex$CriOS/3[0-9](\.|$)', '30.0', '40.0', 2013, 2014, 'pause', (SELECT id FROM type_browser WHERE name = 'Chrome iOS' LIMIT 1)),
  ('Chrome iOS 40', '40.0', 'Chrome iOS: versions 40–49; range [40.0, 50.0)', 'Chrome iOS 40', '$regex$CriOS/4[0-9](\.|$)', '40.0', '50.0', 2015, 2015, 'pause', (SELECT id FROM type_browser WHERE name = 'Chrome iOS' LIMIT 1)),
  ('Chrome iOS 80', '80.0', 'Chrome iOS: versions 80–89; range [80.0, 90.0)', 'Chrome iOS 80', '$regex$CriOS/8[0-9](\.|$)', '80.0', '90.0', 2020, 2023, 'pause', (SELECT id FROM type_browser WHERE name = 'Chrome iOS' LIMIT 1)),
  ('Chrome iOS 90', '90.0', 'Chrome iOS: versions 90–99; range [90.0, 100.0)', 'Chrome iOS 90', '$regex$CriOS/9[0-9](\.|$)', '90.0', '100.0', 2021, 2022, 'pause', (SELECT id FROM type_browser WHERE name = 'Chrome iOS' LIMIT 1)),
  ('Chrome iOS 100', '100.0', 'Chrome iOS: versions 100–109; range [100.0, 110.0)', 'Chrome iOS 100', '$regex$CriOS/10[0-9](\.|$)', '100.0', '110.0', 2022, 2023, 'pause', (SELECT id FROM type_browser WHERE name = 'Chrome iOS' LIMIT 1)),
  ('Chrome iOS 110', '110.0', 'Chrome iOS: versions 110–119; range [110.0, 120.0)', 'Chrome iOS 110', '$regex$CriOS/11[0-9](\.|$)', '110.0', '120.0', 2023, 2023, 'pause', (SELECT id FROM type_browser WHERE name = 'Chrome iOS' LIMIT 1)),
  ('Chrome iOS 120', '120.0', 'Chrome iOS: versions 120–129; range [120.0, 130.0)', 'Chrome iOS 120', '$regex$CriOS/12[0-9](\.|$)', '120.0', '130.0', 2023, 2024, 'pause', (SELECT id FROM type_browser WHERE name = 'Chrome iOS' LIMIT 1)),
  ('Chrome iOS 130', '130.0', 'Chrome iOS: versions 130–139; range [130.0, 140.0)', 'Chrome iOS 130', '$regex$CriOS/13[0-9](\.|$)', '130.0', '140.0', 2024, 2025, 'active', (SELECT id FROM type_browser WHERE name = 'Chrome iOS' LIMIT 1)),
  ('Chrome iOS 140', '140.0', 'Chrome iOS: versions 140–149; range [140.0, 150.0)', 'Chrome iOS 140', '$regex$CriOS/14[0-9](\.|$)', '140.0', '150.0', 2025, 2026, 'active', (SELECT id FROM type_browser WHERE name = 'Chrome iOS' LIMIT 1)),
  ('Chrome iOS 150', '150.0', 'Chrome iOS: versions 150–159; range [150.0, 160.0)', 'Chrome iOS 150', '$regex$CriOS/15[0-9](\.|$)', '150.0', '160.0', 2026, 0, 'active', (SELECT id FROM type_browser WHERE name = 'Chrome iOS' LIMIT 1))
ON CONFLICT (name) DO UPDATE SET
    version = EXCLUDED.version,
    description = EXCLUDED.description,
    match_name_exp = EXCLUDED.match_name_exp,
    match_ua_exp = EXCLUDED.match_ua_exp,
    match_ver_min_exp = EXCLUDED.match_ver_min_exp,
    match_ver_max_exp = EXCLUDED.match_ver_max_exp,
    year_release = EXCLUDED.year_release,
    year_end_support = EXCLUDED.year_end_support,
    active = EXCLUDED.active,
    parent_id = EXCLUDED.parent_id,
    updated_at = NOW();

-- Versions of Firefox iOS
INSERT INTO type_browser (name, version, description, match_name_exp, match_ua_exp, match_ver_min_exp, match_ver_max_exp, year_release, year_end_support, active, parent_id)
VALUES
  ('Firefox iOS 80', '80.0', 'Firefox iOS: versions 80–89; range [80.0, 90.0)', 'Firefox iOS 80', '$regex$FxiOS/8[0-9](\.|$)', '80.0', '90.0', 2020, 2023, 'pause', (SELECT id FROM type_browser WHERE name = 'Firefox iOS' LIMIT 1)),
  ('Firefox iOS 90', '90.0', 'Firefox iOS: versions 90–99; range [90.0, 100.0)', 'Firefox iOS 90', '$regex$FxiOS/9[0-9](\.|$)', '90.0', '100.0', 2021, 2024, 'pause', (SELECT id FROM type_browser WHERE name = 'Firefox iOS' LIMIT 1)),
  ('Firefox iOS 100', '100.0', 'Firefox iOS: versions 100–109; range [100.0, 110.0)', 'Firefox iOS 100', '$regex$FxiOS/10[0-9](\.|$)', '100.0', '110.0', 2022, 2025, 'pause', (SELECT id FROM type_browser WHERE name = 'Firefox iOS' LIMIT 1)),
  ('Firefox iOS 110', '110.0', 'Firefox iOS: versions 110–119; range [110.0, 120.0)', 'Firefox iOS 110', '$regex$FxiOS/11[0-9](\.|$)', '110.0', '120.0', 2023, 2023, 'pause', (SELECT id FROM type_browser WHERE name = 'Firefox iOS' LIMIT 1)),
  ('Firefox iOS 120', '120.0', 'Firefox iOS: versions 120–129; range [120.0, 130.0)', 'Firefox iOS 120', '$regex$FxiOS/12[0-9](\.|$)', '120.0', '130.0', 2023, 2024, 'pause', (SELECT id FROM type_browser WHERE name = 'Firefox iOS' LIMIT 1)),
  ('Firefox iOS 130', '130.0', 'Firefox iOS: versions 130–139; range [130.0, 140.0)', 'Firefox iOS 130', '$regex$FxiOS/13[0-9](\.|$)', '130.0', '140.0', 2024, 2025, 'active', (SELECT id FROM type_browser WHERE name = 'Firefox iOS' LIMIT 1)),
  ('Firefox iOS 140', '140.0', 'Firefox iOS: versions 140–149; range [140.0, 150.0)', 'Firefox iOS 140', '$regex$FxiOS/14[0-9](\.|$)', '140.0', '150.0', 2025, 2026, 'active', (SELECT id FROM type_browser WHERE name = 'Firefox iOS' LIMIT 1)),
  ('Firefox iOS 150', '150.0', 'Firefox iOS: versions 150–159; range [150.0, 160.0)', 'Firefox iOS 150', '$regex$FxiOS/15[0-9](\.|$)', '150.0', '160.0', 2026, 0, 'active', (SELECT id FROM type_browser WHERE name = 'Firefox iOS' LIMIT 1))
ON CONFLICT (name) DO UPDATE SET
    version = EXCLUDED.version,
    description = EXCLUDED.description,
    match_name_exp = EXCLUDED.match_name_exp,
    match_ua_exp = EXCLUDED.match_ua_exp,
    match_ver_min_exp = EXCLUDED.match_ver_min_exp,
    match_ver_max_exp = EXCLUDED.match_ver_max_exp,
    year_release = EXCLUDED.year_release,
    year_end_support = EXCLUDED.year_end_support,
    active = EXCLUDED.active,
    parent_id = EXCLUDED.parent_id,
    updated_at = NOW();

-- Versions of Coc Coc
INSERT INTO type_browser (name, version, description, match_name_exp, match_ua_exp, match_ver_min_exp, match_ver_max_exp, year_release, year_end_support, active, parent_id)
VALUES
  ('Coc Coc 90', '90.0', 'Coc Coc: versions 90–99; range [90.0, 100.0)', 'Coc Coc 90', '$regex$coc_coc_browser/9[0-9](\.|$)', '90.0', '100.0', 2021, 2024, 'active', (SELECT id FROM type_browser WHERE name = 'Coc Coc' LIMIT 1)),
  ('Coc Coc 100', '100.0', 'Coc Coc: versions 100–109; range [100.0, 110.0)', 'Coc Coc 100', '$regex$coc_coc_browser/10[0-9](\.|$)', '100.0', '110.0', 2022, 2025, 'active', (SELECT id FROM type_browser WHERE name = 'Coc Coc' LIMIT 1)),
  ('Coc Coc 110', '110.0', 'Coc Coc: versions 110–119; range [110.0, 120.0)', 'Coc Coc 110', '$regex$coc_coc_browser/11[0-9](\.|$)', '110.0', '120.0', 2023, 2023, 'active', (SELECT id FROM type_browser WHERE name = 'Coc Coc' LIMIT 1)),
  ('Coc Coc 120', '120.0', 'Coc Coc: versions 120–129; range [120.0, 130.0)', 'Coc Coc 120', '$regex$coc_coc_browser/12[0-9](\.|$)', '120.0', '130.0', 2023, 2024, 'active', (SELECT id FROM type_browser WHERE name = 'Coc Coc' LIMIT 1)),
  ('Coc Coc 130', '130.0', 'Coc Coc: versions 130–139; range [130.0, 140.0)', 'Coc Coc 130', '$regex$coc_coc_browser/13[0-9](\.|$)', '130.0', '140.0', 2024, 2025, 'active', (SELECT id FROM type_browser WHERE name = 'Coc Coc' LIMIT 1)),
  ('Coc Coc 140', '140.0', 'Coc Coc: versions 140–149; range [140.0, 150.0)', 'Coc Coc 140', '$regex$coc_coc_browser/14[0-9](\.|$)', '140.0', '150.0', 2025, 0, 'active', (SELECT id FROM type_browser WHERE name = 'Coc Coc' LIMIT 1))
ON CONFLICT (name) DO UPDATE SET
    version = EXCLUDED.version,
    description = EXCLUDED.description,
    match_name_exp = EXCLUDED.match_name_exp,
    match_ua_exp = EXCLUDED.match_ua_exp,
    match_ver_min_exp = EXCLUDED.match_ver_min_exp,
    match_ver_max_exp = EXCLUDED.match_ver_max_exp,
    year_release = EXCLUDED.year_release,
    year_end_support = EXCLUDED.year_end_support,
    active = EXCLUDED.active,
    parent_id = EXCLUDED.parent_id,
    updated_at = NOW();

COMMIT;
