#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""Generate adv_category fixture SQL from hierarchical categories.json."""

from __future__ import annotations

import json
import re
import sys
from typing import Any, Iterator


UPSERT = """ON CONFLICT (iab_code) DO UPDATE SET
  name = EXCLUDED.name,
  description = EXCLUDED.description,
  keywords = EXCLUDED.keywords,
  parent_id = EXCLUDED.parent_id,
  position = EXCLUDED.position,
  updated_at = NOW();"""


def sql_str(value: str) -> str:
    return "'" + value.replace("'", "''") + "'"


def sql_keywords(keywords: list[str] | None) -> str:
    if not keywords:
        return "ARRAY[]::TEXT[]"
    parts = ", ".join(sql_str(k) for k in keywords)
    return f"ARRAY[{parts}]::TEXT[]"


def resolve_iab_code(node: dict[str, Any], parent_code: str | None) -> str:
    """iab_code is optional in JSON; DB still requires a unique non-null value."""
    code = (node.get("iab_code") or "").strip()
    if code:
        return code
    position = int(node.get("position") or 0)
    if parent_code:
        return f"{parent_code}-{position}"
    # Root without explicit code — stable fallback from name + position.
    slug = re.sub(r"[^a-z0-9]+", "-", (node.get("name") or "category").lower()).strip("-")
    return f"GEN-{position}-{slug}" if slug else f"GEN-{position}"


def walk_levels(
    nodes: list[dict[str, Any]],
    parent_code: str | None = None,
) -> Iterator[tuple[str | None, str, dict[str, Any]]]:
    """Yield (parent_code, node_code, node) in BFS order so parents insert before children."""
    level: list[tuple[str | None, dict[str, Any]]] = [(parent_code, n) for n in nodes]
    while level:
        next_level: list[tuple[str | None, dict[str, Any]]] = []
        for parent, node in sorted(level, key=lambda x: int(x[1].get("position") or 0)):
            code = resolve_iab_code(node, parent)
            yield parent, code, node
            for child in node.get("children") or []:
                next_level.append((code, child))
        level = next_level


def generate_sql(tree: list[dict[str, Any]]) -> Iterator[str]:
    yield "-- Generated by categoriesfix.py from categories.json — do not edit by hand."
    yield "BEGIN;"
    yield ""

    # Group by parent code for readability (one INSERT block per parent group)
    groups: dict[str | None, list[tuple[str | None, str, dict[str, Any]]]] = {}
    ordered_parents: list[str | None] = []
    seen: set[str | None] = set()
    for parent, code, node in walk_levels(tree):
        groups.setdefault(parent, []).append((parent, code, node))
        if parent not in seen:
            seen.add(parent)
            ordered_parents.append(parent)

    for parent in ordered_parents:
        items = groups[parent]
        if parent is None:
            yield "-- Root categories"
        else:
            yield f"-- Child categories of {parent}"

        yield "INSERT INTO adv_category (name, description, iab_code, keywords, parent_id, position)"
        yield "VALUES"

        lines = []
        for parent_code, code, node in items:
            if parent_code is None:
                parent_sql = "NULL"
            else:
                parent_sql = f"(SELECT id FROM adv_category WHERE iab_code = {sql_str(parent_code)} LIMIT 1)"
            description = node.get("description") or ""
            lines.append(
                "  ("
                f"{sql_str(node['name'])}, "
                f"{sql_str(description)}, "
                f"{sql_str(code)}, "
                f"{sql_keywords(node.get('keywords') or [])}, "
                f"{parent_sql}, "
                f"{int(node.get('position') or 0)}"
                ")"
            )
        yield ",\n".join(lines)
        yield UPSERT
        yield ""

    yield "COMMIT;"


def main() -> None:
    if len(sys.argv) < 2:
        print("Usage: python categoriesfix.py <categories.json> [output.sql]", file=sys.stderr)
        sys.exit(1)

    json_path = sys.argv[1]
    out_path = sys.argv[2] if len(sys.argv) > 2 else None

    with open(json_path, "r", encoding="utf-8") as f:
        tree = json.load(f)

    sql = "\n".join(generate_sql(tree)) + "\n"
    if out_path:
        with open(out_path, "w", encoding="utf-8") as f:
            f.write(sql)
    else:
        sys.stdout.write(sql)


if __name__ == "__main__":
    main()
