package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"

	"github.com/sspserver/api/internal/server/graphql/models"
)

// ListDeviceTypes is the resolver for the listDeviceTypes field.
func (r *queryResolver) ListDeviceTypes(ctx context.Context) ([]*models.DeviceType, error) {
	return r.device_types.List(ctx)
}
