package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"

	"github.com/sspserver/api/internal/server/graphql/models"
)

// Languages is the resolver for the languages field.
func (r *queryResolver) Languages(ctx context.Context, filter *models.LangListFilter) ([]*models.Lang, error) {
	return r.langs.Languages(ctx, filter)
}
