package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.55

import (
	"context"
	"fmt"

	"github.com/geniusrabbit/blaze-api/server/graphql/models"
)

// Offset is the resolver for the offset field.
func (r *pageResolver) Offset(ctx context.Context, obj *models.Page, data *int) error {
	panic(fmt.Errorf("not implemented: Offset - offset"))
}

type pageResolver struct{ *Resolver }
