package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.63

import (
	"context"

	"github.com/geniusrabbit/blaze-api/server/graphql/connectors"
	models1 "github.com/geniusrabbit/blaze-api/server/graphql/models"
	models2 "github.com/sspserver/api/internal/server/graphql/models"
)

// StatisticAdList is the resolver for the statisticAdList field.
func (r *queryResolver) StatisticAdList(ctx context.Context, filter *models2.StatisticAdListFilter, group []models2.StatisticKey, order []*models2.StatisticAdKeyOrder, page *models1.Page) (*connectors.CollectionConnection[models2.StatisticAdItem, struct{}], error) {
	return r.statistic.Statistic(ctx, filter, group, order, page)
}
