package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.66

import (
	"context"

	"github.com/geniusrabbit/blaze-api/server/graphql/connectors"
	models1 "github.com/geniusrabbit/blaze-api/server/graphql/models"
	"github.com/sspserver/api/internal/server/graphql/generated"
	"github.com/sspserver/api/internal/server/graphql/models"
)

// CreateTrafficRouter is the resolver for the createTrafficRouter field.
func (r *mutationResolver) CreateTrafficRouter(ctx context.Context, input models.TrafficRouterCreateInput) (*models.TrafficRouterPayload, error) {
	return r.trafficrouter.Create(ctx, input)
}

// UpdateTrafficRouter is the resolver for the updateTrafficRouter field.
func (r *mutationResolver) UpdateTrafficRouter(ctx context.Context, id uint64, input models.TrafficRouterUpdateInput) (*models.TrafficRouterPayload, error) {
	return r.trafficrouter.Update(ctx, id, input)
}

// DeleteTrafficRouter is the resolver for the deleteTrafficRouter field.
func (r *mutationResolver) DeleteTrafficRouter(ctx context.Context, id uint64) (*models.TrafficRouterPayload, error) {
	return r.trafficrouter.Delete(ctx, id)
}

// RunTrafficRouter is the resolver for the runTrafficRouter field.
func (r *mutationResolver) RunTrafficRouter(ctx context.Context, id uint64, msg string) (*models1.StatusResponse, error) {
	return r.trafficrouter.Run(ctx, id, msg)
}

// PauseTrafficRouter is the resolver for the pauseTrafficRouter field.
func (r *mutationResolver) PauseTrafficRouter(ctx context.Context, id uint64, msg string) (*models1.StatusResponse, error) {
	return r.trafficrouter.Pause(ctx, id, msg)
}

// TrafficRouter is the resolver for the trafficRouter field.
func (r *queryResolver) TrafficRouter(ctx context.Context, id uint64) (*models.TrafficRouterPayload, error) {
	return r.trafficrouter.Get(ctx, id)
}

// ListTrafficRouters is the resolver for the listTrafficRouters field.
func (r *queryResolver) ListTrafficRouters(ctx context.Context, filter *models.TrafficRouterListFilter, order []*models.TrafficRouterListOrder, page *models1.Page) (*connectors.CollectionConnection[models.TrafficRouter, models.TrafficRouterEdge], error) {
	return r.trafficrouter.List(ctx, filter, order, page)
}

// Account is the resolver for the account field.
func (r *trafficRouterResolver) Account(ctx context.Context, obj *models.TrafficRouter) (*models1.Account, error) {
	if obj.Account != nil || obj.AccountID == 0 {
		return obj.Account, nil
	}
	acc, err := r.Resolver.accounts.Account(ctx, obj.AccountID)
	if err != nil {
		return nil, err
	}
	obj.Account = acc.Account
	return acc.Account, nil
}

// RTBSources is the resolver for the RTBSources field.
func (r *trafficRouterResolver) RTBSources(ctx context.Context, obj *models.TrafficRouter) ([]*models.RTBSource, error) {
	if obj.RTBSources != nil {
		return obj.RTBSources, nil
	}
	list, err := r.Resolver.rtbsource.List(ctx, &models.RTBSourceListFilter{ID: obj.RTBSourceIDs}, nil, nil)
	if err != nil {
		return nil, err
	}
	obj.RTBSources = list.List()
	return obj.RTBSources, nil
}

// TrafficRouter returns generated.TrafficRouterResolver implementation.
func (r *Resolver) TrafficRouter() generated.TrafficRouterResolver { return &trafficRouterResolver{r} }

type trafficRouterResolver struct{ *Resolver }
