type TimeZone {
  name: String!
  lon: Float!
}

type Coordinates {
  lat: Float!
  lon: Float!
}

type Continent {
  """
  Continent ID
  """
  ID: ID64!

  """
  Continent code2
  """
  code2: String!

  """
  Continent name
  """
  name: String!

  """
  List of countries
  """
  countries: [Country!]
}

type Country {
  """
  Country ID
  """
  ID: ID64!

  """
  Country code2
  """
  code2: String!

  """
  Country code3
  """
  code3: String!

  """
  Country name
  """
  name: String!

  """
  Country native name
  """
  nativeName: String!

  """
  Continent code
  """
  continentCode: String!

  """
  Continent object
  """
  continent: Continent!

  """
  Name of the capital city
  """
  capital: String!

  """
  Languages spoken in the country
  """
  languages: [String!]

  """
  Phone codes for the country
  """
  phoneCodes: [String!]

  """
  Time zones for the country
  """
  timeZones: [TimeZone!]

  """
  Coordinates of the country
  """
  coordinates: Coordinates!

  """
  List of currencies
  """
  currency: [String!]

  """
  ISO 3166-2 subdivisions
  """
  regions: [Region!]
}

type Region {
  """
  Region ID
  """
  ID: ID64!

  """
  ISO 3166-2 code (for example US-CA)
  """
  code: String!

  """
  Default English name
  """
  name: String!

  """
  Default name first, then unique alternatives
  """
  names: [String!]

  """
  Subdivision type (State, Province, Parish, ...)
  """
  subdivisionType: String!

  """
  Centroid when known
  """
  coordinates: Coordinates

  """
  Parent country
  """
  country: Country!

  """
  Parent subdivision, if any
  """
  parent: Region
}

###############################################################################
# Query
###############################################################################

extend type Query {
  """
  List of continents
  """
  continents: [Continent!]

  """
  List of countries
  """
  countries: [Country!]

  """
  List of ISO 3166-2 regions, optionally filtered by country ISO-2 code
  """
  regions(countryCode: String): [Region!]

  """
  Region by ISO 3166-2 code
  """
  region(code: String!): Region
}
