name: Build docker image

on:
  # schedule:
  #   - cron: '44 0 * * *'
  workflow_run:
    workflows: [ Tests ]
    types: [ completed ]
  workflow_dispatch:

env:
  GO_VERSION: "1.23"
  GOPRIVATE: github.com/${{ github.repository_owner }}/*
  IMAGE_NAME: ghcr.io/${{ github.repository }}
  DEPLOY_OS_LIST: linux
  BUILD_GOAMD64_LIST: 1 2 3 4
  DEPLOY_ARCH_LIST: amd64 arm64 arm
  BUILD_GOARM_LIST: 6 7
  DEPLOY_COMMIT_NUMBER: ${{ github.sha }}
  DEPLOY_TAG_VALUE: ${{ github.event.workflow_run.head_branch }}
  APP_BUILD_TAGS: nats,postgres,clickhouse,migrate

jobs:
  can_continue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get all changed project improtant files
        id: changed-pi-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            .github/workflows/docker-build.yml
            deploy/production/migrations/**
            deploy/production/Dockerfile
            **.go
            go.mod
            **.yaml
            **.yml
    outputs:
      is: ${{ steps.changed-pi-files.outputs.any_changed }}

  build:
    # Temporarily disabled until switch process in production
    # if: startsWith(github.event.workflow_run.head_branch, 'v')
    needs: [can_continue]
    if: needs.can_continue.outputs.is == 'true' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest
    # environment: "docker hub"

    permissions:
      contents: read
      packages: write
      # This is used to complete the identity challenge
      # with sigstore/fulcio when running outside of PRs.
      id-token: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.workflow_run.head_branch }}
          submodules: true

      - uses: mstachniuk/ci-skip@v1
        with:
          commit-filter: '[skip ci];[ci skip];[docker skip];[skip docker];[doc];[docs]'
          commit-filter-separator: ';'
          fail-fast: true

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: ~${{ env.GO_VERSION }}

      - name: Setup Golang caches
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golang-
            ${{ runner.os }}-

      - name: Build app
        run: make build

      # Workaround: https://github.com/docker/build-push-action/issues/461
      - name: Setup Docker buildx
        uses: docker/setup-buildx-action@v3

      # Login against a Docker registry except on PR
      # https://github.com/docker/login-action
      - name: Log into registry ghcr.io
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # Build and push Docker image with Buildx (don't push on PR)
      # https://github.com/docker/build-push-action
      - name: Build and push Docker image of the service
        id: build-and-push-service
        uses: docker/build-push-action@v4
        with:
          context: .
          file: deploy/production/Dockerfile
          platforms: linux/amd64,linux/amd64/v2,linux/amd64/v3,linux/amd64/v4,linux/arm64,linux/arm/v6,linux/arm/v7,linux/arm64/v8
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ env.IMAGE_NAME }}:${{ github.event.workflow_run.head_branch }},${{ env.IMAGE_NAME }}:latest
