name: Tests

on:
  push:
    tags:
      - v*
    branches:
      - master
      - main
  pull_request:
    branches:
      - master
      - main
  workflow_dispatch:

env:
  GO_VERSION: "1.23"
  GOPRIVATE: github.com/${{ github.repository_owner }}/*
  GIT_CONFIG_CMD: git config --global url."https://${{ secrets.GH_TOKEN }}:x-oauth-basic@github.com/".insteadOf https://github.com/

jobs:
  can_continue:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Get all changed project improtant files
        id: changed-pi-files
        uses: tj-actions/changed-files@v45
        with:
          files: |
            **.go
            go.mod
            **.yaml
            **.yml
    outputs:
      is: ${{ steps.changed-pi-files.outputs.any_changed }}

  lint:
    needs: [ can_continue ]
    if: needs.can_continue.outputs.is == 'true' || github.event_name == 'workflow_dispatch'
    runs-on: ubuntu-latest

    permissions:
      # Required: allow read access to the content for analysis.
      contents: read
      # Optional: allow read access to pull request. Use with `only-new-issues` option.
      pull-requests: read
      # Optional: allow write access to checks to allow the action to annotate code in the PR.
      checks: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Go
        uses: actions/setup-go@v5
        with:
          go-version: ~${{ env.GO_VERSION }}

      - name: Setup Golang caches
        uses: actions/cache@v3
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-golang-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-golang-
            ${{ runner.os }}-

      - name: Setup access for private go modules
        run: ${{ env.GIT_CONFIG_CMD }}

      - name: Install dependencies
        run: go mod download

      - name: Run linters
        uses: golangci/golangci-lint-action@v6
        with:
          version: latest
          skip-cache: true
          args: --timeout=2m --fix
