volumes:
  pgdata:
  zookeeper:
  clickhouse:
  state:

services:
  zookeeper:
    restart: always
    image: zookeeper:3.7
    hostname: zookeeper
    volumes:
      - "zookeeper:/data"
    # environment:
    #   ZOO_MY_ID: 1
    #   ZOO_SERVERS: server.1=0.0.0.0:2888:3888;2181

  clickhouse-server:
    image: clickhouse/clickhouse-server:24.5.1.1763
    user: root
    hostname: clickhouse-server
    restart: on-failure
    links:
      - zookeeper
    depends_on:
      - zookeeper
    volumes:
      - "./clickhouse/config.xml:/etc/clickhouse-server/config.xml:ro"
      - "./clickhouse/conf.d:/etc/clickhouse-server/conf.d:ro"
      - "clickhouse:/clickhouse/"
    healthcheck:
      test: ["CMD", "bash", "-c", "clickhouse-client --query \"SELECT value FROM system.settings WHERE name = 'readonly'\" | grep -q '0'"]
      interval: 10s
      timeout: 5s
      retries: 5
    # ulimit:
    #   nofile:
    #     soft: 262144
    #     hard: 262144

  clickhouse-init:
    image: clickhouse/clickhouse-server
    entrypoint: [ './migrations.sh' ]
    depends_on:
      clickhouse-server:
        condition: service_healthy
      zookeeper:
        condition: service_started
    volumes:
      - "./clickhouse/migrations.sh:/migrations.sh:ro"
      - "../migrations/stats:/archivarius_migrations:ro"
      - "state:/state"

  database:
    image: postgres:16
    restart: always
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready" ]
      interval: 10s
      timeout: 5s
      retries: 5
    env_file:
      - .db.env

  redis:
    image: redis
    restart: always

  nats:
    image: nats
    restart: always
    expose: [ "4222" ]
