include:
  - ./docker-compose-common.yml

services:
  api:
    image: ssp-project/api:latest
    command: ["--run-migrations"]
    ports:
      - "${DOCKER_SERVER_HTTP_PORT}:8080"
      - "${DOCKER_SERVER_PROFILE_PORT}:6060"
    depends_on:
      database:
        condition: service_healthy
      clickhouse-server:
        condition: service_healthy
      clickhouse-init:
        condition: service_started
      redis:
        condition: service_started
      nats:
        condition: service_started
    env_file: ../../.env
